Repository argonui/SCED, pull requests merged in 2022-12, with the labels that each got.

#82 Add Norman's old promo ArkhamDB ID as an alternate
  objects/AllPlayerCards.15bb07/NormanWithers.a5d9bb.gmnotes
  objects/AllPlayerCards.15bb07/NormanWithers.a5d9bb.json
  objects/AllPlayerCards.15bb07/NormanWithers.e0a155.gmnotes
Labels: bug

#83 DeckImporter: Summoned Servitor (Dominance) - BUGFIX
  src/arkhamdb/DeckImporterMain.ttslua
Labels: bugfix

#70 Upgradesheets: Refactoring (addition of 'require' and clean up)
  objects/AllPlayerCards.15bb07/AlchemicalDistillationUpgradeSheet.156166.ttslua
  objects/AllPlayerCards.15bb07/CustomModificationsUpgradeSheet.4104bf.ttslua
  objects/AllPlayerCards.15bb07/DamningTestimonyUpgradeSheet.dc4a62.ttslua
  objects/AllPlayerCards.15bb07/EmpiricalHypothesisUpgradeSheet.0c46a7.ttslua
  objects/AllPlayerCards.15bb07/FriendsinLowPlacesUpgradeSheet.9fb3b9.ttslua
  objects/AllPlayerCards.15bb07/GrizzledUpgradeSheet.ef8f08.ttslua
  objects/AllPlayerCards.15bb07/HonedInstinctUpgradeSheet.ba0e34.ttslua
  objects/AllPlayerCards.15bb07/HuntersArmorUpgradeSheet.d2d01b.ttslua
  objects/AllPlayerCards.15bb07/HyperphysicalShotcasterUpgradeSheet.a4eec2.ttslua
  objects/AllPlayerCards.15bb07/LivingLinkUpgradeSheet.19a05b.ttslua
  objects/AllPlayerCards.15bb07/MakeshiftTrapUpgradeSheet.64dfce.ttslua
  objects/AllPlayerCards.15bb07/PocketMultiToolUpgradeSheet.d706e7.ttslua
  objects/AllPlayerCards.15bb07/PowerWordUpgradeSheet.0d9481.ttslua
  objects/AllPlayerCards.15bb07/RunicAxeUpgradeSheet.be427d.ttslua
  objects/AllPlayerCards.15bb07/SummonedServitorUpgradeSheet.5397a6.ttslua
  objects/AllPlayerCards.15bb07/TheRavenQuillUpgradeSheet.23b96a.ttslua
  src/playercards/customizable/UpgradeSheet.ttslua
Labels: optimization

#58 TSK: clue data
  src/core/DataHelper.ttslua
Labels: official content

#91 Refactor some required files to function as modules
  src/arkhamdb/DeckImporterMain.ttslua
  src/playercards/spawnbag/BondedBag.ttslua
  src/playercards/spawnbag/SpawnBag.ttslua
  src/playercards/spawnbag/UpgradeSheetBag.ttslua
  src/playermat/Zones.ttslua
Labels: optimization

#52 Add card type tags to playermats
  objects/Playermat1White.8b081b.json
  objects/Playermat2Orange.bd0ff4.json
  objects/Playermat3Green.383d8b.json
  objects/Playermat4Red.0840d5.json
Labels: enhancement

#74 Chaos Bag Manager: remove usage of "_G"
  objects/Fan-MadeAccessories.aa8b38/ChaosBagManager.023240.ttslua
Labels: optimization

#78 Clean Up Helper: Remove vector lines
  objects/Fan-MadeAccessories.aa8b38/CleanUpHelper.26cf4b.ttslua
Labels: optimization

#81 Doom Counter Option UI // Clue Counter clean up
  config.json
  modsettings/SnapPoints.json
  objects/DoomCounter.85c4c6.json
  objects/DoomCounter.85c4c6.xml
  objects/MasterClueCounter.4a3aa4.json
  objects/OtherDoominPlay.652ff3.json
  src/core/AgendaDeck.ttslua
  src/core/DoomCounter.ttslua
  src/core/DoomInPlayCounter.ttslua
  src/core/MasterClueCounter.ttslua
  src/playermat/ClueCounter.ttslua
Labels: enhancement, optimization

#79 Displacement tool: visual update
  objects/Fan-MadeAccessories.aa8b38/DisplacementTool.0f1374.json
  objects/Fan-MadeAccessories.aa8b38/DisplacementTool.0f1374.ttslua
  objects/Fan-MadeAccessories.aa8b38/DisplacementTool.0f1374.xml
Labels: optimization

#89 SCED Intro Tour, Part 1
  src/core/tour/TourCard.ttslua
  src/core/tour/TourManager.ttslua
  src/core/tour/TourScript.ttslua
Labels: enhancement

#95 Datahelper: data for 10 tokens (akachi + brand lvl 4)
  src/core/DataHelper.ttslua
Labels: bugfix

#101 Clean up minor file differences
  config.json
  modsettings/CustomUIAssets.json
  modsettings/SnapPoints.json
  objects/DoomCounter.85c4c6.json
  objects/MasterClueCounter.4a3aa4.json
  objects/OtherDoominPlay.652ff3.json
Labels: optimization

#103 Chaos Bag: Stop shuffling onLoad()
  src/chaosbag/ChaosBag.ttslua
Labels: optimization

#102 Clean Up Helper: XML UI for options + code cleanup
  objects/Fan-MadeAccessories.aa8b38/CleanUpHelper.26cf4b.json
  objects/Fan-MadeAccessories.aa8b38/CleanUpHelper.26cf4b.ttslua
  objects/Fan-MadeAccessories.aa8b38/CleanUpHelper.26cf4b.xml
Labels: optimization

#115 Custom Playmat Images: Account for long label
  objects/Fan-MadeAccessories.aa8b38/CustomPlaymatImages.004fe7.ttslua
Labels: optimization, bugfix

#112 Image folder: Extracting the three included headers out of the template
  img/headers/acolyte.png
  img/headers/cover.png
  img/headers/ruins.png
Labels: enhancement

#111 Adding missing empty lines (by building & decomposing)
  objects/ClueCounter.032300.json
  objects/ClueCounter.1769ed.json
  objects/ClueCounter.37be78.json
  objects/ClueCounter.d86b7c.json
  objects/Clues.3f22e5.json
  objects/Clues.4111de.json
  objects/Clues.891403.json
  objects/Clues.db85d6.json
Labels: optimization

#108 Clean Up Helper: Settings UI
  objects/Fan-MadeAccessories.aa8b38/CleanUpHelper.26cf4b.json
  objects/Fan-MadeAccessories.aa8b38/CleanUpHelper.26cf4b.ttslua
  objects/Fan-MadeAccessories.aa8b38/CleanUpHelper.26cf4b.xml
Labels: optimization

#114 Fan-Made Scenarios: Addition of memory functionality, coordinate cleaning of upper table
  objects/ArkhamSCED240Page1-12102022.1dd55c.json
  objects/CoreNightoftheZealot.64a613.json
  objects/EdgeoftheEarth.895eaa.json
  objects/Fan-MadeScenariosCampaignsMiscellany.66e97c.json
  objects/Fan-MadeScenariosCampaignsMiscellany.66e97c.luascriptstate
  objects/Fan-MadeScenariosCampaignsMiscellany.66e97c.ttslua
  objects/Fan-MadeScenariosCampaignsMiscellany.66e97c/Fan-MadeCampaigns.89c32e.json
  objects/Fan-MadeScenariosCampaignsMiscellany.66e97c/Fan-MadeStandaloneScenarios.5db60c.json
  objects/Fan-MadeScenariosCampaignsMiscellany.66e97c/FanContentIndex.2e32b1.json
  objects/Fan-MadeScenariosCampaignsMiscellany.66e97c/SecretObjectivesUltimatums.b2077d.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8.luascriptstate
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9.json
  objects/ReturntoTheCircleUndone.757324.json
  objects/ReturntoTheForgottenAge.479ff3.json
  objects/ReturntoThePathtoCarcosa.e9889a.json
  objects/ReturntotheNightoftheZealot.56270d.json
  objects/TheCircleUndone.63e097.json
  objects/TheDream-Eaters.a16a1a.json
  objects/TheDunwichLegacy.2898f6.json
  objects/ThePathtoCarcosa.aca04c.json
  objects/TheStrangeCaseofDrJekyllandMrHyde.695a4d.json
Labels: enhancement, optimization

#104 Option Panel: Part 3 - Addition of fan made accessories options & code improvement
  config.json
  objects/Fan-MadeAccessories.aa8b38/ChaosBagManager.023240.ttslua
  objects/Fan-MadeAccessories.aa8b38/HandHelper.450688.ttslua
  objects/Fan-MadeAccessories.aa8b38/TokenArranger.022907.luascriptstate
  objects/Fan-MadeAccessories.aa8b38/TokenArranger.022907.ttslua
  src/core/Global.ttslua
  src/tokens/BlessCurseManager.ttslua
  xml/OptionPanel.xml
Labels: enhancement

#110 Use require for investigator counter
  config.json
  objects/Clues.3f22e5.json
  objects/Clues.4111de.json
  objects/Clues.891403.json
  objects/Clues.db85d6.json
  objects/Damage.1f5a0a.json
  objects/Damage.591a45.json
  objects/Damage.e64eec.json
  objects/Damage.eb08d6.json
  objects/Horror.0257d9.json
  objects/Horror.468e88.json
  objects/Horror.7b5729.json
  objects/Horror.beb964.json
  objects/InvestigatorCount.f182ee.json
  objects/Resources.4406f0.json
  objects/Resources.816d84.json
  objects/Resources.a4b60d.json
  objects/Resources.cd15ac.json
  src/core/ActiveInvestigatorCounter.ttslua
  src/core/GenericCounter.ttslua
Labels: optimization

#113 Move official content to require for downloadboxes
  objects/Core.2585f4.json
  objects/Core.2585f4.ttslua
  objects/CoreNightoftheZealot.64a613.json
  objects/CoreNightoftheZealot.64a613.ttslua
  objects/EdgeoftheEarth.895eaa.json
  objects/EdgeoftheEarth.895eaa.ttslua
  objects/EdgeoftheEarthInvestigators.a32f43.json
  objects/EdgeoftheEarthInvestigators.a32f43.ttslua
  objects/ReturntoTheCircleUndone.757324.json
  objects/ReturntoTheCircleUndone.757324.ttslua
  objects/ReturntoTheDunwichLegacy.ce9130.json
  objects/ReturntoTheDunwichLegacy.ce9130.ttslua
  objects/ReturntoTheForgottenAge.479ff3.json
  objects/ReturntoTheForgottenAge.479ff3.ttslua
  objects/ReturntoThePathtoCarcosa.e9889a.json
  objects/ReturntoThePathtoCarcosa.e9889a.ttslua
  objects/ReturntotheNightoftheZealot.56270d.json
  objects/ReturntotheNightoftheZealot.56270d.ttslua
  objects/StarterDeckInvestigators.35fb9c.json
  objects/StarterDeckInvestigators.35fb9c.ttslua
  objects/TheCircleUndone.0dcbe8.json
  objects/TheCircleUndone.0dcbe8.ttslua
  objects/TheCircleUndone.63e097.json
  objects/TheCircleUndone.63e097.ttslua
  objects/TheDream-Eaters.a16a1a.json
  objects/TheDream-Eaters.a16a1a.ttslua
  objects/TheDream-Eaters.a34f34.json
  objects/TheDream-Eaters.a34f34.ttslua
  objects/TheDunwichLegacy.2898f6.json
  objects/TheDunwichLegacy.2898f6.ttslua
  objects/TheDunwichLegacy.5889dd.json
  objects/TheDunwichLegacy.5889dd.ttslua
  objects/TheForgottenAge.03b888.json
  objects/TheForgottenAge.03b888.ttslua
  objects/TheForgottenAge.0bcf19.json
  objects/TheForgottenAge.0bcf19.ttslua
  objects/TheInnsmouthConspiracy.10bd18.json
  objects/TheInnsmouthConspiracy.10bd18.ttslua
  objects/TheInnsmouthConspiracy.465aab.json
  objects/TheInnsmouthConspiracy.465aab.ttslua
  objects/ThePathtoCarcosa.899c3a.json
  objects/ThePathtoCarcosa.899c3a.ttslua
  objects/ThePathtoCarcosa.aca04c.json
  objects/ThePathtoCarcosa.aca04c.ttslua
  objects/TheScarletKeys.300fcc.json
  objects/TheScarletKeys.300fcc.ttslua
  objects/TheScarletKeys.a4fd1b.json
  objects/TheScarletKeys.a4fd1b.ttslua
  src/core/DownloadBox.ttslua
Labels: optimization

#106 Create a unified panel for groups of player cards.
  src/arkhamdb/ArkhamDb.ttslua
  src/playercards/AllCardsBag.ttslua
  src/playercards/PlayerCardPanel.ttslua
  src/playercards/PlayerCardPanelData.ttslua
  src/playercards/PlayerCardSpawner.ttslua
  src/playercards/spawnbag/SpawnBag.ttslua
Labels: enhancement

#116 SCED Intro Tour, Part 4
  modsettings/CustomUIAssets.json
  src/core/tour/TourCard.ttslua
  src/core/tour/TourManager.ttslua
  src/core/tour/TourScript.ttslua
Labels: enhancement

#119 DeckImporter: Updated documentation
  src/arkhamdb/DeckImporterMain.ttslua
Labels: documentation

#117 Option Panel: Part 4 - Rebuilding UI for scrollview // Token Arranger: Bugfix
  modsettings/CustomUIAssets.json
  objects/Fan-MadeAccessories.aa8b38/TokenArranger.022907.ttslua
  src/core/Global.ttslua
  xml/OptionPanel.xml
Labels: enhancement, bugfix

#121 Deck Importer - ArkhamDB: Updated documentation
  src/arkhamdb/ArkhamDb.ttslua
Labels: documentation

#120 Moving token bags a bit up to use free space (plus automatic formatting by MM)
  modsettings/SnapPoints.json
  objects/Cluetokens.31fa39.json
  objects/Connectionmarkers.170f10.json
  objects/Core.2585f4.json
  objects/CoreNightoftheZealot.64a613.json
  objects/DamageTokens.480bda.json
  objects/Doomtokens.47ffc3.json
  objects/EdgeoftheEarth.895eaa.json
  objects/EdgeoftheEarthInvestigators.a32f43.json
  objects/Fan-MadeAccessories.aa8b38/CleanUpHelper.26cf4b.json
  objects/Fan-MadeAccessories.aa8b38/CleanUpHelper.26cf4b.xml
  objects/Fan-MadeScenariosCampaignsMiscellany.66e97c.json
  objects/Horrortokens.c3ecf4.json
  objects/InvestigatorCount.f182ee.json
  objects/LeadInvestigator.acaa93.json
  objects/PhaseTracker.d0c8fa.json
  objects/Resourcetokens.9fadf9.json
  objects/ReturntoTheCircleUndone.757324.json
  objects/ReturntoTheDunwichLegacy.ce9130.json
  objects/ReturntoTheForgottenAge.479ff3.json
  objects/ReturntoThePathtoCarcosa.e9889a.json
  objects/ReturntotheNightoftheZealot.56270d.json
  objects/StarterDeckInvestigators.35fb9c.json
  objects/TheCircleUndone.0dcbe8.json
  objects/TheCircleUndone.63e097.json
  objects/TheDream-Eaters.a16a1a.json
  objects/TheDream-Eaters.a34f34.json
  objects/TheDunwichLegacy.2898f6.json
  objects/TheDunwichLegacy.5889dd.json
  objects/TheForgottenAge.03b888.json
  objects/TheForgottenAge.0bcf19.json
  objects/TheInnsmouthConspiracy.10bd18.json
  objects/TheInnsmouthConspiracy.465aab.json
  objects/ThePathtoCarcosa.899c3a.json
  objects/ThePathtoCarcosa.aca04c.json
  objects/TheScarletKeys.300fcc.json
  objects/TheScarletKeys.a4fd1b.json
Labels: optimization

#123 Option Panel: Part 6 - Addition of "load defaults" functionality
  config.json
  objects/LuaScriptState.luascriptstate
  objects/Playermat1White.8b081b.json
  objects/Playermat1White.8b081b.luascriptstate
  objects/Playermat2Orange.bd0ff4.json
  objects/Playermat2Orange.bd0ff4.luascriptstate
  objects/Playermat3Green.383d8b.json
  objects/Playermat3Green.383d8b.luascriptstate
  objects/Playermat4Red.0840d5.json
  objects/Playermat4Red.0840d5.luascriptstate
  src/core/Global.ttslua
Labels: enhancement

#124 Deck Importer: Account for taboo versions of bonded cards
  src/arkhamdb/ArkhamDb.ttslua
Labels: bugfix

#127 Attachment Helper: Error handling for non-cards
  objects/Fan-MadeAccessories.aa8b38/AttachmentHelper.d45664.ttslua
Labels: optimization

#130 Make Ancestral Knowledge only pull skills from the deck
  src/arkhamdb/DeckImporterMain.ttslua
Labels: bugfix

#122 Card: Short Supply - Moved function from "Hand Helper" directly to card // PlaymatAPI: New functions for playermat getting
  objects/AllPlayerCards.15bb07/ShortSupply.e5f541.json
  objects/AllPlayerCards.15bb07/ShortSupply.e5f541.ttslua
  objects/Fan-MadeAccessories.aa8b38/DisplacementTool.0f1374.json
  objects/Fan-MadeAccessories.aa8b38/HandHelper.450688.json
  objects/Fan-MadeAccessories.aa8b38/HandHelper.450688.ttslua
  src/playermat/PlaymatApi.ttslua
Labels: enhancement, bugfix

#134 Attachment Helper: Moved into infinite bag
  objects/Fan-MadeAccessories.aa8b38.json
  objects/Fan-MadeAccessories.aa8b38/AttachmentHelper.7f4976.json
  objects/Fan-MadeAccessories.aa8b38/AttachmentHelper.7f4976/AttachmentHelper.d45664.json
  objects/Fan-MadeAccessories.aa8b38/AttachmentHelper.7f4976/AttachmentHelper.d45664.ttslua
Labels: enhancement
