Repository argonui/SCED, pull requests merged in 2022-11, with the labels that each got.

#25 updated global script
  src/chaosbag/ChaosBagStatTracker.ttslua
  src/core/Global.ttslua
Labels: enhancement

#27 updating various of my tools
  objects/Fan-MadeAccessories.aa8b38/AttachmentHelper.d45664.ttslua
  objects/Fan-MadeAccessories.aa8b38/ChaosBagManager.023240.ttslua
  objects/Fan-MadeAccessories.aa8b38/CleanUpHelper.26cf4b.ttslua
  objects/Fan-MadeAccessories.aa8b38/SearchAssistant.17aed0.json
  objects/Fan-MadeAccessories.aa8b38/SearchAssistant.17aed0.ttslua
Labels: enhancement

#40 using require for download boxes
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801/AllorNothing.72ab92.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801/AllorNothing.72ab92.ttslua
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801/BadBlood.451eaa.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801/BadBlood.451eaa.ttslua
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801/BytheBook.cc7eb3.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801/BytheBook.cc7eb3.ttslua
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801/ReadorDie.9e73fa.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801/ReadorDie.9e73fa.ttslua
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801/RedTideRising.5302f2.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801/RedTideRising.5302f2.ttslua
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/CarnevaleofHorrors.23dd51.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/CarnevaleofHorrors.23dd51.ttslua
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/CurseoftheRougarou.db7039.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/CurseoftheRougarou.db7039.ttslua
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/FortuneandFolly.0dce91.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/FortuneandFolly.0dce91.ttslua
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/GuardiansoftheAbyss.ee987d.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/GuardiansoftheAbyss.ee987d.ttslua
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/MachinationsThroughTime.3c4f3c.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/MachinationsThroughTime.3c4f3c.ttslua
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/MurderattheExcelsiorHotel.01d780.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/MurderattheExcelsiorHotel.01d780.ttslua
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/TheBlobthatAteEverything.4dee5a.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/TheBlobthatAteEverything.4dee5a.ttslua
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/TheLabyrinthsofLunacy.4c173f.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/TheLabyrinthsofLunacy.4c173f.ttslua
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/WaroftheOuterGods.fc7674.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9/WaroftheOuterGods.fc7674.ttslua
  src/core/DownloadBox.ttslua
Labels: optimization

#38 adding missing information for FaF
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9.json
  src/core/DataHelper.ttslua
Labels: official content

#21 updated playermats and added InvestigatorSkillTracker
  config.json
  objects/Agility.2c3f8d.json
  objects/Agility.d4df33.json
  objects/Combat.19026b.json
  objects/Combat.9136c6.json
  objects/Combat.93a48b.json
  objects/Combat.b661a6.json
  objects/Intellect.0016fc.json
  objects/Intellect.4ca990.json
  objects/Intellect.c1fe65.json
  objects/InvestigatorSkillTracker.af7ed7.json
  objects/InvestigatorSkillTracker.b4a5f7.json
  objects/InvestigatorSkillTracker.e598c2.json
  objects/InvestigatorSkillTracker.e74881.json
  objects/Playermat1White.8b081b.json
  objects/Playermat1White.8b081b.ttslua
  objects/Playermat2Orange.bd0ff4.json
  objects/Playermat2Orange.bd0ff4.ttslua
  objects/Playermat3Green.383d8b.json
  objects/Playermat3Green.383d8b.ttslua
  objects/Playermat4Red.0840d5.json
  objects/Playermat4Red.0840d5.ttslua
  objects/Willpower.85a8ed.json
  objects/Willpower.8b6743.json
  objects/Willpower.afc290.json
  src/playermat/InvestigatorSkillTracker.ttslua
  src/playermat/Playmat.ttslua
  src/playermat/SkillToken.ttslua
Labels: enhancement

#48 Create SpawnBag to replace card memory bags
  objects/Bonded.c5261f.json
  src/playercards/PlayerCardSpawner.ttslua
  src/playercards/spawnbag/BondedBag.ttslua
  src/playercards/spawnbag/SpawnBag.ttslua
Labels: optimization

#53 Tweak stat tracker positions to be consistent above each playmat
  objects/InvestigatorSkillTracker.af7ed7.json
  objects/InvestigatorSkillTracker.b4a5f7.json
  objects/InvestigatorSkillTracker.e74881.json
Labels: optimization

#54 Add skill selection capability to Living Ink
  objects/AllPlayerCards.15bb07/LivingLinkUpgradeSheet.19a05b.json
  src/playercards/customizable/LivingInkUpgradeSheet.ttslua
  src/playercards/spawnbag/UpgradeSheetBag.ttslua
Labels: enhancement

#57 raising tokens, combining and updating source scripts
  objects/CustomDataHelper.2547b3.json
  objects/Custom_Model.032300.json
  objects/Custom_Model.1769ed.json
  objects/Custom_Model.37be78.json
  objects/Custom_Model.d86b7c.json
  objects/Damage.1f5a0a.json
  objects/Damage.591a45.json
  objects/Damage.e64eec.json
  objects/Damage.eb08d6.json
  objects/DataHelper.708279.json
  objects/Fan-MadeAccessories.aa8b38/CleanUpHelper.26cf4b.ttslua
  objects/Horror.0257d9.json
  objects/Horror.468e88.json
  objects/Horror.7b5729.json
  objects/Horror.beb964.json
  objects/LolaNeutral.26a0a0.json
  objects/LolaNeutral.460250.json
  objects/LolaNeutral.49bf4b.json
  objects/LolaNeutral.637e17.json
  objects/LolaNeutral.719ff4.json
  objects/LolaNeutral.7ffb43.json
  objects/LolaNeutral.8a496e.json
  objects/LolaNeutral.9312d8.json
  objects/LolaNeutral.a1e2a3.json
  objects/LolaNeutral.a7c0f0.json
  objects/LolaNeutral.b8409d.json
  objects/LolaNeutral.bf7cc9.json
  objects/LolaNeutral.bfcaf4.json
  objects/LolaNeutral.d7910b.json
  objects/LolaNeutral.e003fe.json
  objects/LolaNeutral.e1ab8d.json
  objects/Playermat1White.8b081b.json
  objects/Playermat2Orange.bd0ff4.json
  objects/Playermat3Green.383d8b.json
  objects/Playermat4Red.0840d5.json
  objects/Resources.4406f0.json
  objects/Resources.816d84.json
  objects/Resources.a4b60d.json
  objects/Resources.cd15ac.json
  src/playermat/DamageTracker.ttslua
  src/playermat/GenericCounter.ttslua
  src/playermat/HorrorTracker.ttslua
  src/playermat/Playmat.ttslua
  src/playermat/ResourceTracker.ttslua
Labels: optimization

#65 Fix multiple bugs with uses
  src/playermat/Playmat.ttslua
Labels: bug

#71 Doom in Play Counter: displaying ignore tag by default
  modsettings/ComponentTags.json
Labels: bug

#73 Rebundling because of Mod Manager Update (better handling of XML)
  config.json
  objects/Fan-MadeAccessories.aa8b38/DisplacementTool.0f1374.json
  objects/Fan-MadeAccessories.aa8b38/DisplacementTool.0f1374.xml
  objects/LegacyAssets.7165a9/TokenArranger.4825a7.json
  objects/LegacyAssets.7165a9/TokenArranger.4825a7.xml
  objects/Root.xml
Labels: optimization

#75 Handle On the Mend when loading from ArkhamDB
  src/arkhamdb/DeckImporterMain.ttslua
  src/core/PlayArea.ttslua
Labels: bug

#72 Clean Up Helper: exclude "chaos bag" from cleanup
  objects/Fan-MadeAccessories.aa8b38/CleanUpHelper.26cf4b.ttslua
Labels: enhancement

#76 Add startsInHand handling for the deck loader
  objects/AllPlayerCards.15bb07/DarkInsight.f08934.gmnotes
  src/arkhamdb/DeckImporterMain.ttslua
Labels: bug
