Repository argonui/SCED, pull requests merged in 2023-01, with the labels that each got.

#142 Remove double start message for the intro tour
  src/core/tour/TourStarter.ttslua
Labels: bugfix

#140 Add Unified Player Card panel
  config.json
  objects/PlayerCards.2d30ee.json
  src/arkhamdb/ArkhamDb.ttslua
  src/playercards/AllCardsBag.ttslua
  src/playercards/PlayerCardPanel.ttslua
  src/playercards/PlayerCardPanelData.ttslua
Labels: enhancement

#139 Draw location connections automatically
  src/core/PlayArea.ttslua
Labels: enhancement

#150 Token Manager: Re-enables tooltip and blanks the name for tokens
  objects/TokenSource.124381/ClueDoom.a3fb6c.json
  objects/TokenSource.124381/ClueDoom.a40a48.json
  objects/TokenSource.124381/Resource.00d19a.json
  src/core/token/TokenManager.ttslua
Labels: bugfix

#149 Option: Clickable clues bugfix
  src/playermat/Playmat.ttslua
Labels: bugfix

#135 Option Panel: Adding more fan-made accessories
  objects/Fan-MadeAccessories.aa8b38/ChaosBagManager.023240.json
  objects/LuaScriptState.luascriptstate
  src/core/Global.ttslua
  xml/OptionPanel.xml
Labels: enhancement

#145 Chaos Bag Manager: Elder sign button and rotation fix
  objects/Fan-MadeAccessories.aa8b38/ChaosBagManager.023240.ttslua
  src/core/Global.ttslua
Labels: bugfix

#144 Hand Helper: Fix playmat api connection
  objects/Fan-MadeAccessories.aa8b38/HandHelper.450688.ttslua
Labels: bugfix

#152 Token Remover: Exclude chaos tokens + code cleanup
  config.json
  modsettings/TabStates.json
  objects/TokenRemover.0a5a29.json
  src/util/TokenRemover.ttslua
Labels: enhancement

#148 Option: Clickable resource tokens
  objects/TokenSource.124381.json
  objects/TokenSource.124381/ResourceCounter.498ec0.json
  src/core/GenericCounter.ttslua
  src/core/Global.ttslua
  src/core/token/TokenManager.ttslua
  src/playermat/Playmat.ttslua
  xml/OptionPanel.xml
Labels: enhancement

#143 Playmat Image Swapper: Fix variable name and declaration
  src/core/PlayArea.ttslua
  src/core/PlayAreaSelector.ttslua
  src/core/token/TokenManager.ttslua
Labels: bugfix

#151 Option: Location snap tags for play area
  modsettings/SnapPoints.json
  objects/Connectionmarkers.170f10/Custom_Tile.7234af.json
  objects/LuaScriptState.luascriptstate
  objects/Playarea.721ba2.json
  src/core/Global.ttslua
  src/core/PlayArea.ttslua
  src/core/PlayAreaApi.ttslua
  xml/OptionPanel.xml
Labels: enhancement

#146 Playmat - Upkeep: Dont unexhaust investigators
  src/playermat/Playmat.ttslua
Labels: bugfix

#133 Deck Importer: configuration cleanup
  src/arkhamdb/Configuration.ttslua
Labels: optimization

#147 Token Manager: Bugfix for spawning of multiple tokens and default rotation of damage and horror tokens
  objects/TokenSource.124381/Damage.cd2a02.json
  objects/TokenSource.124381/Horror.36be72.json
  src/core/token/TokenManager.ttslua
Labels: bugfix

#153 Moving the accessories to the "src" folder
  objects/Fan-MadeAccessories.aa8b38/AttachmentHelper.d45664.json
  objects/Fan-MadeAccessories.aa8b38/ChaosBagManager.023240.json
  objects/Fan-MadeAccessories.aa8b38/CleanUpHelper.26cf4b.json
  objects/Fan-MadeAccessories.aa8b38/CustomPlaymatImages.004fe7.json
  objects/Fan-MadeAccessories.aa8b38/DisplacementTool.0f1374.json
  objects/Fan-MadeAccessories.aa8b38/HandHelper.450688.json
  objects/Fan-MadeAccessories.aa8b38/SearchAssistant.17aed0.json
  objects/Fan-MadeAccessories.aa8b38/TokenArranger.022907.json
  src/accessories/AttachmentHelper.ttslua
  src/accessories/ChaosBagManager.ttslua
  src/accessories/CleanUpHelper.ttslua
  src/accessories/CustomPlaymatImages.ttslua
  src/accessories/DisplacementTool.ttslua
  src/accessories/HandHelper.ttslua
  src/accessories/SearchAssistant.ttslua
  src/accessories/TokenArranger.ttslua
Labels: optimization

#161 Playermat: Handle deleted small action token
  src/playermat/Playmat.ttslua
Labels: bugfix

#160 Option Panel: new group (general settings) & more compact layout
  img/headers/acolyte.png
  img/headers/cover.png
  img/headers/olive.png
  img/headers/ruins.png
  modsettings/CustomUIAssets.json
  xml/OptionPanel.xml
Labels: optimization

#159 Playarea image swapper: Update position, remove personal information
  objects/PlaymatImageSwapper.b7b45b.json
  src/core/PlayAreaSelector.ttslua
Labels: optimization

#162 Search Assistant: Refactor and added to Option Panel
  objects/Fan-MadeAccessories.aa8b38/SearchAssistant.17aed0.json
  objects/LuaScriptState.luascriptstate
  src/accessories/SearchAssistant.ttslua
  src/core/Global.ttslua
  xml/OptionPanel.xml
Labels: optimization, bugfix

#156 Token Spawner: updated code, orphan removal
  objects/Connectionmarkers.b118af/Custom_Tile.7234af.json
  objects/TokenSource.124381.json
  objects/TokenSource.124381/Path.7234af.json
  src/util/TokenSpawner.ttslua
Labels: optimization

#164 Draw 1 Button: bugfix for reference
  src/playermat/Playmat.ttslua
Labels: bugfix

#158 New utility file: TokenChecker
  objects/AllPlayerCards.15bb07/Unrelenting1.45386d.ttslua
  objects/Blesstokens.afa06b.json
  objects/Blesstokens.afa06b/Bless.b2b7be.json
  objects/Blesstokens.afa06b/Custom_Tile.09aa04.json
  objects/Blesstokens.afa06b/Custom_Tile.5ca99d.json
  objects/Blesstokens.afa06b/Custom_Tile.90e57c.json
  objects/Blesstokens.afa06b/Custom_Tile.b2b7be.json
  objects/Blesstokens.afa06b/Custom_Tile.bc1c12.json
  objects/Blesstokens.afa06b/Custom_Tile.eb0b16.json
  objects/Cursetokens.bd0253.json
  objects/Cursetokens.bd0253/Curse.678891.json
  objects/Cursetokens.bd0253/Custom_Tile.5b224c.json
  objects/Cursetokens.bd0253/Custom_Tile.678891.json
  objects/Cursetokens.bd0253/Custom_Tile.adec97.json
  objects/Cursetokens.bd0253/Custom_Tile.b92c2b.json
  src/core/Global.ttslua
  src/core/token/TokenChecker.ttslua
  src/playermat/Playmat.ttslua
  src/util/TokenRemover.ttslua
Labels: enhancement

#170 Playmat: Discarding playercards bugfix
  src/playermat/Playmat.ttslua
Labels: bugfix

#167 Option Panel: Accessories spawn position update
  objects/Fan-MadeAccessories.aa8b38/CYOACampaignGuides.e87ea2.luascriptstate
  src/core/Global.ttslua
Labels: bugfix

#176 Bugfix: Adding missing location tag to connection token states
  objects/Connectionmarkers.170f10/Custom_Tile.7234af.json
  objects/TokenSource.124381/Path.7234af.json
Labels: bugfix

#175 Bugfix for hand zone GUIDS
  src/core/token/TokenSpawnTracker.ttslua
Labels: bugfix

#174 Bugfix for replenishing with Resource Counters
  objects/Connectionmarkers.170f10/Custom_Tile.7234af.json
  objects/DamageTokens.480bda/Custom_Token.cd2a02.json
  objects/DamageTokens.93f4a0/Custom_Token.cd2a02.json
  objects/DamageTokens.b0ef6c/Custom_Token.cd2a02.json
  objects/Horrortokens.7bd2a0/Horror.36be72.json
  objects/Horrortokens.ae1a4e/Horror.36be72.json
  objects/Horrortokens.c3ecf4/Horror.36be72.json
  objects/Resourcetokens.0168ae/Custom_Token.00d19a.json
  objects/Resourcetokens.9fadf9/Custom_Token.00d19a.json
  objects/Resourcetokens.fd617a/Custom_Token.00d19a.json
  objects/TokenSource.124381/Damage.cd2a02.json
  objects/TokenSource.124381/Horror.36be72.json
  objects/TokenSource.124381/Path.7234af.json
  objects/TokenSource.124381/ResourceCounter.498ec0.json
  src/core/token/TokenManager.ttslua
  src/playermat/Playmat.ttslua
Labels: bugfix

#180 Playarea: Only trigger onPickup for cards, documentation update
  src/core/PlayArea.ttslua
Labels: documentation, bugfix

#181 Bottom menu: Increase offset from 60 to 80
  xml/Global.xml
  xml/OptionPanel.xml
Labels: bugfix

#188 Clean Up Helper: fixed typo for TokenSpawnTrackerApi
  src/accessories/CleanUpHelper.ttslua
Labels: bugfix

#190 Taboo Cards with higher resolution
  objects/AllPlayerCards.15bb07/BlackMarket2Taboo.8e4d23.json
  objects/AllPlayerCards.15bb07/Counterspell2Taboo.118264.json
  objects/AllPlayerCards.15bb07/CrisisofIdentityTaboo.55be9c.json
  objects/AllPlayerCards.15bb07/CyclopeanHammer5Taboo.a39c3b.json
  objects/AllPlayerCards.15bb07/DarkProphecyTaboo.94cdf6.json
  objects/AllPlayerCards.15bb07/DavidRenfieldTaboo.7a73c4.json
  objects/AllPlayerCards.15bb07/EonChart1Taboo.4d4ffb.json
  objects/AllPlayerCards.15bb07/EonChart4Taboo.b925cf.json
  objects/AllPlayerCards.15bb07/FluteoftheOuterGods4Taboo.669c4e.json
  objects/AllPlayerCards.15bb07/GenBeauregard3Taboo.ab32db.json
  objects/AllPlayerCards.15bb07/JeremiahKirbyTaboo.71e4a0.json
  objects/AllPlayerCards.15bb07/JewelofAureolus3Taboo.213e21.json
  objects/AllPlayerCards.15bb07/LolaHayesTaboo.475460.json
  objects/AllPlayerCards.15bb07/MandyThompsonTaboo.754b0a.json
  objects/AllPlayerCards.15bb07/MrRookTaboo.7fe728.json
  objects/AllPlayerCards.15bb07/ProphesiaeProfana5Taboo.3c2561.json
  objects/AllPlayerCards.15bb07/RiteofEquilibrium5Taboo.d45a81.json
  objects/AllPlayerCards.15bb07/RitualCandlesTaboo.e99e75.json
  objects/AllPlayerCards.15bb07/SignumCrucis2Taboo.119880.json
  objects/AllPlayerCards.15bb07/StrangeSolution4Taboo.e95ddb.json
  objects/AllPlayerCards.15bb07/VoiceofRaTaboo.77f7f3.json
Labels: enhancement, official content

#189 Standalone Scenario Box: increasing size by 30%
  objects/OfficialStandaloneChallengeScenarios.0ef5c8.luascriptstate
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/StandaloneScenarios.77a5f9.json
Labels: optimization

#196 Fixing doom rotation for bottom token bag
  objects/Doomtokens.47ffc3/Custom_Tile.a3fb6c.json
Labels: bugfix

#197 Short Supply: Bugfix
  objects/AllPlayerCards.15bb07/ShortSupply.e5f541.ttslua
Labels: bugfix

#199 TSK: Adding story assets to playercard bag
  objects/AllPlayerCards.15bb07.json
  objects/AllPlayerCards.15bb07/AgentAriQuinn.d61c6a.gmnotes
  objects/AllPlayerCards.15bb07/AgentAriQuinn.d61c6a.json
  objects/AllPlayerCards.15bb07/DrDewiIrawan.c76a06.gmnotes
  objects/AllPlayerCards.15bb07/DrDewiIrawan.c76a06.json
  objects/AllPlayerCards.15bb07/ExpeditedTicket.8fbd1b.gmnotes
  objects/AllPlayerCards.15bb07/ExpeditedTicket.8fbd1b.json
  objects/AllPlayerCards.15bb07/FoundationIntel.a72f6f.gmnotes
  objects/AllPlayerCards.15bb07/FoundationIntel.a72f6f.json
  objects/AllPlayerCards.15bb07/InspectorFlint.8247a5.gmnotes
  objects/AllPlayerCards.15bb07/InspectorFlint.8247a5.json
  objects/AllPlayerCards.15bb07/ParadimensionalUnderstanding.3c3dfa.gmnotes
  objects/AllPlayerCards.15bb07/ParadimensionalUnderstanding.3c3dfa.json
  objects/Cluetokens.11e0cf/Custom_Tile.a3fb6c.json
  objects/Cluetokens.31fa39/Custom_Tile.a3fb6c.json
  objects/Cluetokens.3b2550/Custom_Tile.a3fb6c.json
  objects/Cluetokens.fae2f6/Custom_Tile.a3fb6c.json
  objects/DamageTokens.480bda/Custom_Token.cd2a02.json
  objects/DamageTokens.93f4a0/Custom_Token.cd2a02.json
  objects/DamageTokens.b0ef6c/Custom_Token.cd2a02.json
  objects/Doomtokens.16724b/Custom_Tile.a3fb6c.json
  objects/Doomtokens.16fcd6/Custom_Tile.a3fb6c.json
  objects/Doomtokens.47ffc3/Custom_Tile.a3fb6c.json
  objects/Doomtokens.b015d8/Custom_Tile.a3fb6c.json
  objects/FogOfWarTrigger.3aab97.json
  objects/GameData.3dbe47.json
  objects/Horrortokens.7bd2a0/Horror.36be72.json
  objects/Horrortokens.ae1a4e/Horror.36be72.json
  objects/Horrortokens.c3ecf4/Horror.36be72.json
  objects/Resourcetokens.0168ae/Custom_Token.00d19a.json
  objects/Resourcetokens.9fadf9/Custom_Token.00d19a.json
  objects/Resourcetokens.fd617a/Custom_Token.00d19a.json
  objects/TokenSource.124381/ClueDoom.a3fb6c.json
  objects/TokenSource.124381/Damage.cd2a02.json
  objects/TokenSource.124381/Horror.36be72.json
  objects/TokenSource.124381/Path.7234af.json
  objects/TokenSource.124381/Resource.00d19a.json
  objects/TokenSource.124381/ResourceCounter.498ec0.json
Labels: official content

#202 Bugfix: file name
  config.json
  objects/ArkhamSCE300-1272023-Page1.f873a8.json
Labels: bugfix

#203 Custom Data Helper referring bugfix
  src/accessories/CleanUpHelper.ttslua
  src/core/PlayAreaSelector.ttslua
Labels: bugfix

#204 Doom token on mythos area: rotation fix
  objects/Doomtokens.b015d8/Custom_Tile.a3fb6c.json
Labels: bugfix
