Repository argonui/SCED, pull requests merged in 2023-09, with the labels that each got.

#358 Adding initial "The Feast of Hemlock Vale" cards
  objects/AllPlayerCards.15bb07.json
  objects/AllPlayerCards.15bb07/ChemistrySet.da9727.gmnotes
  objects/AllPlayerCards.15bb07/ChemistrySet.da9727.json
  objects/AllPlayerCards.15bb07/DrCharlesWestIII.72efed.gmnotes
  objects/AllPlayerCards.15bb07/DrCharlesWestIII.72efed.json
  objects/AllPlayerCards.15bb07/LongShot.dc8c4d.gmnotes
  objects/AllPlayerCards.15bb07/LongShot.dc8c4d.json
  objects/AllPlayerCards.15bb07/Microscope.48be49.gmnotes
  objects/AllPlayerCards.15bb07/Microscope.48be49.json
  objects/AllPlayerCards.15bb07/Pitchfork.45a724.gmnotes
  objects/AllPlayerCards.15bb07/Pitchfork.45a724.json
  objects/AllPlayerCards.15bb07/PushedtotheLimit.e0f396.gmnotes
  objects/AllPlayerCards.15bb07/PushedtotheLimit.e0f396.json
  objects/AllPlayerCards.15bb07/RavenousMyconid.0aa967.gmnotes
  objects/AllPlayerCards.15bb07/RavenousMyconid.0aa967.json
  objects/AllPlayerCards.15bb07/SparrowMask.975d79.gmnotes
  objects/AllPlayerCards.15bb07/SparrowMask.975d79.json
  objects/AllPlayerCards.15bb07/StallforTime.7b6ed1.gmnotes
  objects/AllPlayerCards.15bb07/StallforTime.7b6ed1.json
  objects/AllPlayerCards.15bb07/UncannyGrowth.6543e6.gmnotes
  objects/AllPlayerCards.15bb07/UncannyGrowth.6543e6.json
  objects/AllPlayerCards.15bb07/Well-Funded.96fbfa.gmnotes
  objects/AllPlayerCards.15bb07/Well-Funded.96fbfa.json
  objects/AllPlayerCards.15bb07/WrongPlaceRightTime.d5944e.gmnotes
  objects/AllPlayerCards.15bb07/WrongPlaceRightTime.d5944e.json
  objects/LeakedItems.42cd6e.json
  objects/PlayerCards.2d30ee.json
  src/playercards/PlayerCardPanel.ttslua
  src/playercards/PlayerCardPanelData.ttslua
Labels: official content

#376 Fix: Underworld Market Helper breaks after saving & loading
  objects/Fan-MadeAccessories.aa8b38/UnderworldMarketHelper.3650ea.ttslua
Labels: bugfix

#373 Springfield 1903: metadata correction
  objects/AllPlayerCards.15bb07/SpringfieldM19034.a7944d.gmnotes
Labels: bugfix

#375 Master Clue Counter: increased readability
  objects/MasterClueCounter.4a3aa4.json
  src/core/MasterClueCounter.ttslua
Labels: optimization

#366 Resource Hotkey: load correct state
  src/util/TokenSpawnTool.ttslua
Labels: enhancement

#367 Upgradesheets: removal of obsolete code
  src/playercards/customizable/AlchemicalDistillationUpgradeSheet.ttslua
  src/playercards/customizable/CustomModificationsUpgradeSheet.ttslua
  src/playercards/customizable/DamningTestimonyUpgradeSheet.ttslua
  src/playercards/customizable/EmpiricalHypothesisUpgradeSheet.ttslua
  src/playercards/customizable/FriendsinLowPlacesUpgradeSheet.ttslua
  src/playercards/customizable/GrizzledUpgradeSheet.ttslua
  src/playercards/customizable/HonedInstinctUpgradeSheet.ttslua
  src/playercards/customizable/HuntersArmorUpgradeSheet.ttslua
  src/playercards/customizable/HyperphysicalShotcasterUpgradeSheet.ttslua
  src/playercards/customizable/LivingInkUpgradeSheet.ttslua
  src/playercards/customizable/MakeshiftTrapUpgradeSheet.ttslua
  src/playercards/customizable/PocketMultiToolUpgradeSheet.ttslua
  src/playercards/customizable/PowerWordUpgradeSheet.ttslua
  src/playercards/customizable/RunicAxeUpgradeSheet.ttslua
  src/playercards/customizable/SummonedServitorUpgradeSheet.ttslua
Labels: optimization

#378 Uses spawning: additional option
  objects/AllPlayerCards.15bb07/ArchaicGlyphs.cbfc12.gmnotes
  objects/AllPlayerCards.15bb07/ArchiveofConduits.8023f5.gmnotes
  objects/AllPlayerCards.15bb07/BorrowedTime3.0db666.gmnotes
  objects/AllPlayerCards.15bb07/CrypticGrimoire4.416f12.gmnotes
  objects/AllPlayerCards.15bb07/CrypticGrimoire4.e8b179.gmnotes
  objects/AllPlayerCards.15bb07/DarrellsKodak.caa382.gmnotes
  objects/AllPlayerCards.15bb07/DissectionTools.95ca5d.gmnotes
  objects/AllPlayerCards.15bb07/EmpiricalHypothesis.62c67d.gmnotes
  objects/AllPlayerCards.15bb07/GreenManMedallion.c729ab.gmnotes
  objects/AllPlayerCards.15bb07/Hawk-EyeFoldingCamera.5ada0a.gmnotes
  objects/AllPlayerCards.15bb07/MichaelLeigh5.573765.gmnotes
  objects/AllPlayerCards.15bb07/PurifyingCorruption4.ac9763.gmnotes
  objects/AllPlayerCards.15bb07/ResearchNotes.a37bd4.gmnotes
  objects/AllPlayerCards.15bb07/SoulSanctification3.52f6d6.gmnotes
  objects/AllPlayerCards.15bb07/TheHungeringBlade1.2d94ed.gmnotes
  objects/LuaScriptState.luascriptstate
  src/core/Global.ttslua
  src/core/token/TokenManager.ttslua
  xml/OptionPanel.xml
Labels: enhancement

#377 Encounter card drawing / discard: moved code and fixed TTS merge bug
  src/core/Global.ttslua
  src/core/MythosArea.ttslua
  src/core/MythosAreaApi.ttslua
  src/playermat/Playmat.ttslua
Labels: enhancement, bugfix

#365 Token Arranger: more resilience to latency
  src/accessories/TokenArranger.ttslua
Labels: optimization, bugfix

#379 Added placeholder boxes for fan-made content
  objects/Community-CreatedPlayerCardsInvestigators.ed4ca7.json
  objects/Community-CreatedPlayerCardsInvestigators.ed4ca7/BuffytheVampireSlayer.6bf40f.json
  objects/Community-CreatedPlayerCardsInvestigators.ed4ca7/CircusExMortisInvestigatorExpansion.195936.json
  objects/Community-CreatedPlayerCardsInvestigators.ed4ca7/CityofSecrets.1ee775.json
  objects/Community-CreatedPlayerCardsInvestigators.ed4ca7/TheRedCoterie.de13e3.json
  objects/Community-CreatedPlayerCardsInvestigators.ed4ca7/TheSandsOfMemphisInvestigatorExpansion.073201.json
  objects/Fan-MadeScenariosCampaignsMiscellany.66e97c/Fan-MadeCampaigns.89c32e.json
  objects/Fan-MadeScenariosCampaignsMiscellany.66e97c/Fan-MadeCampaigns.89c32e/HeartofDarkness.cc95ff.json
  objects/Fan-MadeScenariosCampaignsMiscellany.66e97c/Fan-MadeCampaigns.89c32e/SoulsofDarkness.a94e6b.json
  objects/Fan-MadeScenariosCampaignsMiscellany.66e97c/Fan-MadeCampaigns.89c32e/TheSandsOfMemphisCampaignExpansion.2634e3.json
Labels: custom content
