Repository argonui/SCED, pull requests merged in 2023-06, with the labels that each got.

#305 updated ID range for parallel investigators
  src/arkhamdb/ArkhamDb.ttslua
Labels: bugfix

#300 Chaos Token Stat Tracker: sorted printing
  src/core/Global.ttslua
Labels: optimization

#309 Resource tokens - correcting rotation
  objects/Resourcetokens.0168ae/Resource.4cd3f6.json
  objects/Resourcetokens.9fadf9/Resource.4cd3f6.json
  objects/Resourcetokens.fd617a/Resource.4cd3f6.json
Labels: bugfix

#308 keep context menu open for specific cards with "sealing"
  src/playercards/CardsThatSealTokens.ttslua
  src/playercards/cards/DarkRitual.ttslua
  src/playercards/cards/FavoroftheMoon1.ttslua
  src/playercards/cards/FavoroftheSun1.ttslua
  src/playercards/cards/FluteoftheOuterGods4.ttslua
  src/playercards/cards/RadiantSmite1.ttslua
  src/playercards/cards/ShieldofFaith2.ttslua
  src/playercards/cards/Unrelenting1.ttslua
Labels: optimization

#307 Upkeep: ready face-down cards, removed legacy code
  src/playermat/Playmat.ttslua
Labels: optimization

#310 Victory Display: trigger update from clue hotkey
  src/core/GameKeyHandler.ttslua
  src/core/VictoryDisplay.ttslua
  src/core/VictoryDisplayApi.ttslua
Labels: optimization

#313 Update player mat handling of customizable cards
  objects/Playermat1White.8b081b.ttslua
  objects/Playermat2Orange.bd0ff4.ttslua
  objects/Playermat3Green.383d8b.ttslua
  objects/Playermat4Red.0840d5.ttslua
  src/playercards/customizable/UpgradeSheetLibrary.ttslua
  src/playermat/Playmat.ttslua
  src/playermat/PlaymatApi.ttslua
Labels: bug, enhancement, optimization

#320 SoundCubeApi: fixed scoping
  src/core/SoundCubeApi.ttslua
Labels: optimization

#318 Add camera_ignore tags and reduce X_BUFFER
  objects/TableDivider.612072.json
  objects/TableDivider.75937e.json
  objects/TableDivider.8646eb.json
  objects/TableDivider.975c39.json
  objects/VictoryDisplay.6ccd6d.json
  src/core/NavigationOverlayHandler.ttslua
  src/playermat/Playmat.ttslua
Labels: bugfix

#316 Upkeep: keep state for replenishing cards
  src/core/token/TokenManager.ttslua
  src/playermat/Playmat.ttslua
Labels: bugfix
