Repository argonui/SCED, pull requests merged in 2023-03, with the labels that each got.

#219 Displacement Tool: redraw connections after displacement
  src/core/PlayArea.ttslua
Labels: bugfix

#221 Underworld Market: stop including permanent cards
  src/arkhamdb/DeckImporterMain.ttslua
Labels: bugfix

#217 Attachment Helper: support for decks of cards, added backpack image and misc. updates
  objects/Fan-MadeAccessories.aa8b38/AttachmentHelper.7f4976/AttachmentHelper.d45664.json
  objects/Fan-MadeAccessories.aa8b38/AttachmentHelper.7f4976/AttachmentHelper.d45664.ttslua
  src/accessories/AttachmentHelper.ttslua
Labels: enhancement, optimization

#220 Hand Helper: code updates
  objects/Fan-MadeAccessories.aa8b38/HandHelper.450688.json
  src/accessories/HandHelper.ttslua
  src/core/Global.ttslua
  src/playermat/Playmat.ttslua
  src/playermat/PlaymatApi.ttslua
Labels: enhancement, optimization

#218 Token Arranger: token metadata support and misc. updates
  modsettings/ComponentTags.json
  objects/Fan-MadeAccessories.aa8b38/TokenArranger.022907.json
  objects/Fan-MadeAccessories.aa8b38/TokenArranger.022907.luascriptstate
  src/accessories/TokenArranger.ttslua
  src/accessories/TokenArrangerApi.ttslua
  src/chaosbag/BlessCurseManager.ttslua
  src/core/Global.ttslua
  src/core/MythosArea.ttslua
Labels: enhancement, optimization

#222 Adding MythosAreaAPI
  src/accessories/TokenArranger.ttslua
  src/accessories/TokenArrangerApi.ttslua
  src/core/MythosArea.ttslua
  src/core/MythosAreaApi.ttslua
Labels: optimization

#225 Victory Display: added button to highlight counted cards
  src/core/PlayArea.ttslua
  src/core/PlayAreaApi.ttslua
  src/core/VictoryDisplay.ttslua
Labels: enhancement

#229 Living Ink typo correction
  objects/AllPlayerCards.15bb07.json
  objects/AllPlayerCards.15bb07/LivingInkUpgradeSheet.19a05b.json
Labels: bugfix

#230 Victory Display: bug fix for cards without victory points
  src/core/VictoryDisplay.ttslua
Labels: bugfix

#236 Attachment Helper: adding picture for "Stick to the Plan"
  src/accessories/AttachmentHelper.ttslua
Labels: enhancement

#235 Playermat: spawning accessories relative to mat
  src/core/Global.ttslua
  src/playermat/Playmat.ttslua
  src/playermat/PlaymatApi.ttslua
  src/playermat/Zones.ttslua
Labels: enhancement

#233 Bless/Curse Manager: image change (added transparent border)
  objects/BlessCurseManager.5933fb.json
Labels: bugfix

#232 Data Helper: removal of deprecated functionality
  src/core/DataHelper.ttslua
  src/core/Global.ttslua
Labels: optimization

#231 Trash: adding context menu function to empty
  objects/Trash.147e80.json
  objects/Trash.4b8594.json
  objects/Trash.5f896a.json
  objects/Trash.70b9f6.json
  objects/Trash.f7b6c8.json
  src/util/Trashcan.ttslua
Labels: enhancement

#237 Replenishing cards: Bugfix to allow overcharging
  src/playermat/Playmat.ttslua
Labels: bugfix

#242 TSK Investigator Expansion Rules Insert
  objects/RulebooksGuidesandTablets.fcfa7f.json
  objects/RulebooksGuidesandTablets.fcfa7f/TheScarletKeys-InvestigatorExpansion.e331fc.json
Labels: official content

#227 Summoned Servitor Dominance upgrade sheet buttons
  objects/AllPlayerCards.15bb07/SummonedServitorUpgradeSheet.5397a6.json
  src/arkhamdb/DeckImporterMain.ttslua
  src/playercards/customizable/SummonedServitorUpgradeSheet.ttslua
Labels: enhancement

#238 Colorblindfriendly action tokens
  config.json
  objects/Neutral.012577.json
  objects/Neutral.0329cc.json
  objects/Neutral.04765b.json
  objects/Neutral.183dbe.json
  objects/Neutral.1cb302.json
  objects/Neutral.2691e1.json
  objects/Neutral.26a0a0.json
  objects/Neutral.271b17.json
  objects/Neutral.429bb3.json
  objects/Neutral.460250.json
  objects/Neutral.49bf4b.json
  objects/Neutral.5825ca.json
  objects/Neutral.5bafdf.json
  objects/Neutral.5bec40.json
  objects/Neutral.637e17.json
  objects/Neutral.719ff4.json
  objects/Neutral.748245.json
  objects/Neutral.7ffb43.json
  objects/Neutral.8a496e.json
  objects/Neutral.9312d8.json
  objects/Neutral.a1e2a3.json
  objects/Neutral.a7c0f0.json
  objects/Neutral.af1927.json
  objects/Neutral.b71036.json
  objects/Neutral.b80db6.json
  objects/Neutral.b8409d.json
  objects/Neutral.bbc5d4.json
  objects/Neutral.bf7cc9.json
  objects/Neutral.bfcaf4.json
  objects/Neutral.d7910b.json
  objects/Neutral.e003fe.json
  objects/Neutral.e1ab8d.json
Labels: enhancement

#240 Data Helper: uncomment deprecated tables for tokenmanager
  src/core/DataHelper.ttslua
Labels: bugfix

#244 Add alt view angle for sideways decks
  src/playercards/PlayerCardSpawner.ttslua
Labels: enhancement
