Repository argonui/SCED, pull requests merged in 2024-06, with the labels that each got.

#701 Updated GameKeyHandler code
  src/core/GameKeyHandler.ttslua
Labels: documentation, optimization

#693 Updated DES detection for Hand Helper // Increased search area
  objects/OptionPanelSource.830bd0/HandHelper.450688.json
  src/accessories/HandHelper.ttslua
  src/playermat/Playmat.ttslua
  src/playermat/PlaymatApi.ttslua
Labels: optimization

#706 Search Assistant: Increased delay on deck shuffling
  src/accessories/SearchAssistant.ttslua
Labels: bugfix

#707 Turned the additional cards bag into a proper box
  objects/AdditionalPlayerCards.2cba6b.json
  objects/Search-A-Card.24051a.json
Labels: optimization

#705 Clean Up Helper: Misc updates
  src/accessories/CleanUpHelper.ttslua
  src/core/MythosAreaApi.ttslua
Labels: optimization

#708 Fixed taboo investigator card ratio
  objects/AllPlayerCards.15bb07/LolaHayesTaboo.52956d.json
  objects/AllPlayerCards.15bb07/MandyThompsonTaboo.4f3637.json
  objects/AllPlayerCards.15bb07/TrishScarboroughTaboo.2ce76d.json
Labels: bugfix

#709 Changed default behaviour to 3 tokens
  src/playermat/Playmat.ttslua
Labels: bugfix

#714 Updated Attachment Helper
  src/accessories/AttachmentHelper.ttslua
Labels: enhancement, optimization

#713 Updated investigator scaling
  src/playercards/PlayerCardSpawner.ttslua
  src/playermat/Playmat.ttslua
Labels: enhancement

#717 Updated deck importer
  objects/ArkhamDBDeckImporter.a28140.json
  src/arkhamdb/DeckImporter.ttslua
  src/arkhamdb/DeckImporterUi.ttslua
Labels: enhancement

#716 Adds helpers for automatic token redrawing and replacement
  objects/AllPlayerCards.15bb07/ClaypoolsFurs.c1f999.json
  objects/AllPlayerCards.15bb07/CustomModifications.d2252d.json
  objects/AllPlayerCards.15bb07/FalseCovenant2.3442f5.json
  objects/AllPlayerCards.15bb07/HeavyFurs.275450.json
  objects/AllPlayerCards.15bb07/WendyAdams.15e40d.json
  objects/AllPlayerCards.15bb07/WendyAdams.fc1d17.json
  objects/AllPlayerCards.15bb07/WendyAdamsParallelBack.4232d9.json
  src/chaosbag/BlessCurseManager.ttslua
  src/chaosbag/BlessCurseManagerApi.ttslua
  src/chaosbag/ChaosBagApi.ttslua
  src/core/Global.ttslua
  src/playercards/CardsThatRedrawTokens.ttslua
  src/playercards/cards/ClaypoolsFurs.ttslua
  src/playercards/cards/CustomModifications.ttslua
  src/playercards/cards/FalseCovenant.ttslua
  src/playercards/cards/HeavyFurs.ttslua
  src/playercards/cards/NkosiMabati3.ttslua
  src/playercards/cards/WendyAdams.ttslua
Labels: enhancement

#723 Table cleanup
  config.json
  objects/AdditionalPlayerCards.2cba6b.json
  objects/AdditionalPlayerCards.2cba6b/AliceLuxley2.94f23b.gmnotes
  objects/AdditionalPlayerCards.2cba6b/AliceLuxley2.94f23b.json
  objects/AdditionalPlayerCards.2cba6b/DragonPole3.a20aef.gmnotes
  objects/AdditionalPlayerCards.2cba6b/DragonPole3.a20aef.json
  objects/AdditionalPlayerCards.2cba6b/FineClothes3.5cb973.gmnotes
  objects/AdditionalPlayerCards.2cba6b/FineClothes3.5cb973.json
  objects/AdditionalPlayerCards.2cba6b/SwordCane2.9c32e2.gmnotes
  objects/AdditionalPlayerCards.2cba6b/SwordCane2.9c32e2.json
  objects/BarkhamHorror.308439.json
  objects/BarkhamHorror.308439/TheMeddlingofMeowlathotep.d02940.json
  objects/Fan-MadeAccessories.aa8b38.json
  objects/Fan-MadeAccessories.aa8b38/DescriptivePhaseTracker.b171c8.json
  objects/Fan-MadeAccessories.aa8b38/DescriptivePhaseTracker.b171c8.ttslua
  objects/LatestFAQ.faqfaq.json
  objects/LeakedItems.42cd6e.json
  objects/LegacyAssets.7165a9.json
  objects/LegacyAssets.7165a9/CustomDataHelper.2547b3.json
  objects/LegacyAssets.7165a9/Double-SidedResource.bc81cb.json
  objects/RulebooksGuidesandTablets.fcfa7f.json
  objects/RulebooksGuidesandTablets.fcfa7f/In-depthArkhamHorrorTTStutorial.51cb8d.json
  objects/RulebooksGuidesandTablets.fcfa7f/LearntoPlay.49f237.json
  objects/RulebooksGuidesandTablets.fcfa7f/MysteriousChanting-CustomContentBlog.18bd3a.json
  objects/RulebooksGuidesandTablets.fcfa7f/OfficialFAQ.7fc24e.json
  objects/RulebooksGuidesandTablets.fcfa7f/OfficialLearntoPlayVideo.39ec3d.json
  objects/RulebooksGuidesandTablets.fcfa7f/Rulepop-QuickRulesReferenceSite.b78dae.json
  objects/RulebooksGuidesandTablets.fcfa7f/StarterDecklists.9cd82a.json
  objects/RulebooksGuidesandTablets.fcfa7f/SuggestedAmbientTracks.5b268d.json
  objects/TokenSpawningReference.f8b3a7.json
  src/accessories/PhaseTracker.ttslua
Labels: optimization

#722 New option: Enable all card helpers
  objects/AllPlayerCards.15bb07/TheChthonianStone3.a775ad.json
  objects/LuaScriptState.luascriptstate
  src/chaosbag/ChaosBagApi.ttslua
  src/core/Global.ttslua
  src/playercards/CardsThatRedrawTokens.ttslua
  src/playercards/CardsWithHelper.ttslua
  src/playercards/cards/BookofLivingMyths.ttslua
  src/playercards/cards/ClaypoolsFurs.ttslua
  src/playercards/cards/CustomModifications.ttslua
  src/playercards/cards/EmpiricalHypothesis.ttslua
  src/playercards/cards/FalseCovenant.ttslua
  src/playercards/cards/HeavyFurs.ttslua
  src/playercards/cards/NkosiMabati3.ttslua
  src/playercards/cards/TheChthonianStone3.ttslua
  src/playercards/cards/WellConnected.ttslua
  src/playercards/cards/WendyAdams.ttslua
  src/playermat/Playmat.ttslua
  xml/Global/OptionPanel.xml
  xml/playercards/BookofLivingMyths.xml
Labels: enhancement, optimization

#724 Bugfixes for CardsWithHelpers
  src/core/Global.ttslua
  src/playercards/cards/BookofLivingMyths.ttslua
  src/playercards/cards/EmpiricalHypothesis.ttslua
  src/playercards/cards/WellConnected.ttslua
Labels: bugfix

#718 Playermat update
  config.json
  objects/ChaosBagStatTracker.766620.json
  objects/FlexTableControl.bd69bd.ttslua
  objects/LuaScriptState.luascriptstate
  objects/OptionPanelSource.830bd0/DisplacementTool.0f1374.json
  objects/OptionPanelSource.830bd0/SearchAssistant.17aed0.json
  objects/PlayAreaImageSwapper.b7b45b.json
  objects/Playermat1White.8b081b.json
  objects/Playermat1White.8b081b.luascriptstate
  objects/Playermat2Orange.bd0ff4.json
  objects/Playermat2Orange.bd0ff4.luascriptstate
  objects/Playermat3Green.383d8b.json
  objects/Playermat3Green.383d8b.luascriptstate
  objects/Playermat4Red.0840d5.json
  objects/Playermat4Red.0840d5.luascriptstate
  objects/TokenSource.124381/UniversalActionAbilityToken.834ad5.json
  src/accessories/CampaignImporterExporter.ttslua
  src/accessories/CleanUpHelper.ttslua
  src/accessories/HandHelper.ttslua
  src/accessories/PhaseTracker.ttslua
  src/accessories/SearchAssistant.ttslua
  src/accessories/UnderworldMarketHelper.ttslua
  src/arkhamdb/ArkhamDb.ttslua
  src/arkhamdb/DeckImporter.ttslua
  src/core/DataHelper.ttslua
  src/core/DoomInPlayCounter.ttslua
  src/core/GameKeyHandler.ttslua
  src/core/Global.ttslua
  src/core/MasterClueCounter.ttslua
  src/core/MythosArea.ttslua
  src/core/NavigationOverlayHandler.ttslua
  src/core/PlayArea.ttslua
  src/core/PlayAreaApi.ttslua
  src/core/PlayAreaSelector.ttslua
  src/core/token/TokenManager.ttslua
  src/playercards/CardSearch.ttslua
  src/playercards/CardsThatSealTokens.ttslua
  src/playercards/cards/BookofLivingMyths.ttslua
  src/playercards/cards/EmpiricalHypothesis.ttslua
  src/playercards/cards/FamilyInheritance.ttslua
  src/playercards/cards/ScrollofSecrets.ttslua
  src/playercards/cards/ShortSupply.ttslua
  src/playercards/cards/Tekeli-li.ttslua
  src/playercards/cards/WellConnected.ttslua
  src/playercards/customizable/UpgradeSheetLibrary.ttslua
  src/playermat/ClueCounter.ttslua
  src/playermat/Playermat.ttslua
  src/playermat/PlayermatApi.ttslua
  src/playermat/Zones.ttslua
  src/util/TokenSpawnTool.ttslua
  xml/Global/OptionPanel.xml
Labels: enhancement

#726 Added right-click function to specify a trait for RBW button
  src/playercards/AllCardsBag.ttslua
  src/playercards/AllCardsBagApi.ttslua
  src/playercards/PlayerCardPanel.ttslua
Labels: enhancement

#728 Set correct scale for spawning mini cards
  objects/AllPlayerCards.15bb07/AgnesBaker.e53693.json
  src/playercards/PlayerCardSpawner.ttslua
Labels: bugfix

#725 Updated Scroll of Secrets menu
  src/playercards/cards/ScrollofSecrets.ttslua
  src/playermat/PlayermatApi.ttslua
Labels: optimization

#729 Updated Clean Up Helper
  src/accessories/CleanUpHelper.ttslua
Labels: optimization
