Repository argonui/SCED, pull requests merged in 2024-01, with the labels that each got.

#522 QoL update for play area
  src/accessories/CleanUpHelper.ttslua
  src/core/Global.ttslua
  src/core/PlayArea.ttslua
Labels: bugfix

#523 Discard Object Hotkey: fixed wrong bracket placement
  src/core/GameKeyHandler.ttslua
Labels: bugfix

#531 Doom Counter: omit the threshold from the broadcast if doom is reset
  src/core/DoomCounter.ttslua
Labels: enhancement

#529 Added placeholder for "Relics of the Past" challenge scenario
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801.json
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801.luascriptstate
  objects/OfficialStandaloneChallengeScenarios.0ef5c8/ChallengeScenarios.9f6801/RelicsofthePast.0d6da1.json
Labels: official content

#532 Fixed bracket placement for "Remove One Use" hotkey
  src/core/GameKeyHandler.ttslua
Labels: bugfix

#527 Added "DeckLib"
  src/core/MythosArea.ttslua
  src/playermat/Playmat.ttslua
  src/util/DeckLib.ttslua
Labels: enhancement

#530 Misc. code improvements for ChaosBag / Encounter card drawing
  src/chaosbag/ChaosBagApi.ttslua
  src/core/GUIDReferenceHandler.ttslua
  src/core/Global.ttslua
  src/core/MythosArea.ttslua
  src/core/MythosAreaApi.ttslua
  src/playermat/Playmat.ttslua
Labels: optimization

#537 Multihand improvements
  src/core/GameKeyHandler.ttslua
  src/core/Global.ttslua
  src/core/NavigationOverlayApi.ttslua
  src/core/NavigationOverlayHandler.ttslua
  src/playermat/PlaymatApi.ttslua
Labels: enhancement

#541 Investigator Skill Tracker: code improvement + bugfix
  src/playermat/InvestigatorSkillTracker.ttslua
Labels: optimization, bugfix

#543 added mouse mask
  objects/AllPlayerCards.15bb07.json
  objects/AllPlayerCards.15bb07/MouseMask.32ad21.gmnotes
  objects/AllPlayerCards.15bb07/MouseMask.32ad21.json
Labels: official content

#544 added button to reshuffle encounter discard pile into deck
  objects/MythosArea.9f334f.json
  src/core/MythosArea.ttslua
  xml/MythosArea.xml
Labels: enhancement

#547 Bugfix for Clean Up Helper
  src/accessories/CleanUpHelper.ttslua
Labels: bugfix

#546 Bugfix for encounter shuffle button
  objects/MythosArea.9f334f.json
  xml/MythosArea.xml
Labels: bugfix

#524 Turned playermat hider into a dropdown option
  config.json
  objects/LuaScriptState.luascriptstate
  objects/OptionPanelSource.830bd0.json
  objects/OptionPanelSource.830bd0/PlayermatHider.a758b2.json
  objects/PlayermatClickInterceptor.3dbe55.json
  objects/PlayermatClickInterceptor.3dbe55.ttslua
  src/accessories/CleanUpHelper.ttslua
  src/accessories/PlayermatHider.ttslua
  src/core/GUIDReferenceApi.ttslua
  src/core/GUIDReferenceHandler.ttslua
  src/core/GameKeyHandler.ttslua
  src/core/Global.ttslua
  src/core/NavigationOverlayApi.ttslua
  src/core/NavigationOverlayHandler.ttslua
  src/playermat/PlaymatApi.ttslua
  xml/Global/OptionPanel.xml
  xml/accessories/PlayermatHider.xml
Labels: enhancement

#538 Update to blurse manager
  config.json
  objects/BlessCurseManager.5933fb.json
  objects/Blesstokens.afa06b.json
  objects/Blesstokens.afa06b/Bless.b2b7be.json
  objects/ChaosBagZone.83ef06.json
  objects/Cursetokens.bd0253.json
  objects/Cursetokens.bd0253/Curse.678891.json
  src/chaosbag/BlessCurseManager.ttslua
  src/chaosbag/BlessCurseManagerApi.ttslua
  src/chaosbag/ChaosBagApi.ttslua
  src/core/GameKeyHandler.ttslua
  src/core/Global.ttslua
  src/playercards/CardsThatSealTokens.ttslua
  src/playercards/cards/Nephthys4.ttslua
  src/playermat/Playmat.ttslua
Labels: optimization

#533 Campaign Exporter Improvements
  objects/CampaignImporterExporter.334ee3.json
  src/accessories/CampaignImporterExporter.ttslua
  src/core/GUIDReferenceHandler.ttslua
  src/playercards/AllCardsBag.ttslua
Labels: optimization

#550 Misc. code fixes
  src/accessories/SearchAssistant.ttslua
  src/accessories/TokenArrangerApi.ttslua
  src/accessories/UnderworldMarketHelper.ttslua
  src/arkhamdb/DeckImporterMain.ttslua
  src/chaosbag/BlessCurseManagerApi.ttslua
  src/core/Global.ttslua
  src/core/PlayArea.ttslua
  src/core/PlayAreaApi.ttslua
  src/core/VictoryDisplay.ttslua
  src/core/token/TokenManager.ttslua
  src/playercards/PlayerCardPanel.ttslua
  src/playercards/PlayerCardSpawner.ttslua
  src/playercards/SpawnBag.ttslua
  src/playercards/cards/FamilyInheritance.ttslua
  src/playermat/Zones.ttslua
  src/util/TokenSpawnTool.ttslua
Labels: documentation, bugfix

#553 Fixed some duplicate deckids
  objects/AllPlayerCards.15bb07/Accursed.e91c5e.json
  objects/AllPlayerCards.15bb07/ChemistrySet.da9727.json
  objects/AllPlayerCards.15bb07/DrCharlesWestIII.72efed.json
  objects/AllPlayerCards.15bb07/EldritchTongue.e8765a.json
  objects/AllPlayerCards.15bb07/FalseSurrender.adf28e.json
  objects/AllPlayerCards.15bb07/LolaHayesTaboo.52956d.json
  objects/AllPlayerCards.15bb07/LongShot.dc8c4d.json
  objects/AllPlayerCards.15bb07/MandyThompsonTaboo.4f3637.json
  objects/AllPlayerCards.15bb07/Microscope.48be49.json
  objects/AllPlayerCards.15bb07/Pitchfork.45a724.json
  objects/AllPlayerCards.15bb07/Purified.294d6a.json
  objects/AllPlayerCards.15bb07/PushedtotheLimit.e0f396.json
  objects/AllPlayerCards.15bb07/RavenousMyconid.0aa967.json
  objects/AllPlayerCards.15bb07/RexMurphyTaboo.0a5491.json
  objects/AllPlayerCards.15bb07/SparrowMask.975d79.json
  objects/AllPlayerCards.15bb07/StallforTime.7b6ed1.json
  objects/AllPlayerCards.15bb07/TrishScarboroughTaboo.2ce76d.json
  objects/AllPlayerCards.15bb07/UncannyGrowth.6543e6.json
  objects/AllPlayerCards.15bb07/Well-Funded.96fbfa.json
  objects/AllPlayerCards.15bb07/WrongPlaceRightTime.d5944e.json
Labels: bugfix

#551 Added simple detection for disabled physics
  config.json
  objects/PhysicsDetector.b300d8.json
  src/core/PhysicsDetector.ttslua
Labels: enhancement

#555 Added nil handling for import instructions
  src/arkhamdb/ArkhamDb.ttslua
Labels: bugfix

#557 Tour update
  modsettings/CameraStates.json
  modsettings/CustomUIAssets.json
  src/core/tour/TourCard.ttslua
  src/core/tour/TourManager.ttslua
  src/core/tour/TourScript.ttslua
Labels: enhancement

#558 Bugfix for take clue hotkey
  src/core/GameKeyHandler.ttslua
Labels: bugfix
