Repository argonui/SCED, pull requests merged in 2024-05, with the labels that each got.

#671 Updated campaign exporter and option panel
  modsettings/CustomUIAssets.json
  src/accessories/CampaignImporterExporter.ttslua
  src/core/Global.ttslua
  xml/Global/OptionPanel.xml
Labels: enhancement, bugfix

#668 Added upper limit for bonded cards
  objects/AllPlayerCards.15bb07/BiancaDieKatz.897a94.gmnotes
  objects/AllPlayerCards.15bb07/BrokenDiadem5.b6d35d.gmnotes
  objects/AllPlayerCards.15bb07/CrystallizerofDreams.6692de.gmnotes
  objects/AllPlayerCards.15bb07/DreamDiary.b81dcf.gmnotes
  objects/AllPlayerCards.15bb07/DreamDiary3.5f9a10.gmnotes
  objects/AllPlayerCards.15bb07/DreamDiary3.e5f9cb.gmnotes
  objects/AllPlayerCards.15bb07/DreamDiary3.ea40f6.gmnotes
  objects/AllPlayerCards.15bb07/EmptyVessel4.c0d236.gmnotes
  objects/AllPlayerCards.15bb07/EyesofValusia4.e7bfbe.gmnotes
  objects/AllPlayerCards.15bb07/FluxStabilizer.55990a.gmnotes
  objects/AllPlayerCards.15bb07/GateBox.b8c891.gmnotes
  objects/AllPlayerCards.15bb07/HallowedMirror.312d38.gmnotes
  objects/AllPlayerCards.15bb07/HallowedMirror3.78858f.gmnotes
  objects/AllPlayerCards.15bb07/HankSamson.3764cd.gmnotes
  objects/AllPlayerCards.15bb07/MiracleWish5.d78d4a.gmnotes
  objects/AllPlayerCards.15bb07/MissDoyle1.e1aedf.gmnotes
  objects/AllPlayerCards.15bb07/NightmareBauble3.d6f6f1.gmnotes
  objects/AllPlayerCards.15bb07/OccultLexicon.5d6728.gmnotes
  objects/AllPlayerCards.15bb07/OccultLexicon3.71d99c.gmnotes
  objects/AllPlayerCards.15bb07/RavenousMyconid.0aa967.gmnotes
  objects/AllPlayerCards.15bb07/RavenousMyconid4.ab2752.gmnotes
  objects/AllPlayerCards.15bb07/RavenousMyconid4.baa926.gmnotes
  objects/AllPlayerCards.15bb07/RavenousMyconid4.df93ca.gmnotes
  objects/AllPlayerCards.15bb07/RodofCarnamagos.66ec64.gmnotes
  objects/AllPlayerCards.15bb07/RodofCarnamagos2.d8ef99.gmnotes
  objects/AllPlayerCards.15bb07/SealoftheElders5.d2b649.gmnotes
  objects/AllPlayerCards.15bb07/SegmentofOnyx1.ff9f23.gmnotes
  objects/AllPlayerCards.15bb07/Stargazing1.968a26.gmnotes
  objects/AllPlayerCards.15bb07/SummonedHound1.ab4fb3.gmnotes
  objects/AllPlayerCards.15bb07/TheHungeringBlade1.2d94ed.gmnotes
  src/arkhamdb/ArkhamDb.ttslua
Labels: enhancement

#670 Fixed action token handling for Clean Up Helper
  src/accessories/CleanUpHelper.ttslua
Labels: bugfix

#666 Bugfix for spawning a single damage / horror
  src/core/token/TokenManager.ttslua
Labels: bugfix

#665 Code maintenance for MythosArea
  src/core/MythosArea.ttslua
Labels: documentation

#673 Updated PlaymatApi for Explore and Tekeli-li helpers
  src/core/MythosArea.ttslua
  src/core/MythosAreaApi.ttslua
  src/playermat/Playmat.ttslua
  src/playermat/PlaymatApi.ttslua
Labels: enhancement

#682 Added function to get owner of an object
  src/core/GUIDReferenceApi.ttslua
  src/core/GUIDReferenceHandler.ttslua
  src/core/Global.ttslua
Labels: documentation, optimization

#679 [Play Area] Code maintenance and API function for tracked locations
  src/core/PlayArea.ttslua
  src/core/PlayAreaApi.ttslua
Labels: documentation, optimization

#681 New hotkey to take cards into threat area
  src/core/GameKeyHandler.ttslua
Labels: enhancement

#684 Implemented deckLib for SearchAssistent
  objects/OptionPanelSource.830bd0/DisplacementTool.0f1374.json
  src/accessories/SearchAssistant.ttslua
  src/core/Global.ttslua
Labels: optimization, bugfix

#686 Bugfix for cards without IDs
  src/playercards/AllCardsBag.ttslua
Labels: bugfix

#687 Bugfix for drawing an encounter card while there is not deck / discard
  src/core/MythosArea.ttslua
Labels: bugfix

#688 Added "continue" for empty hotfix bags
  src/playercards/AllCardsBag.ttslua
Labels: bugfix

#694 Turned "DoNotReady" into a tag
  objects/AllPlayerCards.15bb07/JacobMorrison3.aa38d0.json
  src/playermat/Playmat.ttslua
Labels: enhancement

#691 Updated Drawing Tool
  config.json
  modsettings/TabStates.json
  objects/DrawingTool.280086.json
  src/util/ConnectionDrawingTool.ttslua
Labels: optimization

#695 Bugfixes for Deck Importer
  src/arkhamdb/ArkhamDb.ttslua
Labels: bugfix

#696 Fixed scale for Trish
  objects/AllPlayerCards.15bb07/TrishScarboroughTaboo.2ce76d.json
Labels: bugfix

#689 Added regular JSON parser as fallback
  src/playercards/AllCardsBag.ttslua
Labels: bugfix

#690 Various updates to the Token Arranger
  objects/TokenArranger.022907.luascriptstate
  src/accessories/TokenArranger.ttslua
Labels: optimization, bugfix

#692 Added playermat slot symbol saving to campaign exporter
  src/accessories/CampaignImporterExporter.ttslua
  src/playermat/Playmat.ttslua
  src/playermat/PlaymatApi.ttslua
Labels: enhancement, bugfix

#699 Redraw the playmat slot XML when a player joins
  src/core/Global.ttslua
  src/playermat/PlaymatApi.ttslua
Labels: bugfix

#700 Added confirmation dialog to discard hotkey
  src/core/GameKeyHandler.ttslua
Labels: optimization

#698 Updated player card panel
  objects/PlayerCards.2d30ee.json
  src/arkhamdb/DeckImporterUi.ttslua
  src/playercards/AllCardsBag.ttslua
  src/playercards/AllCardsBagApi.ttslua
  src/playercards/PlayerCardPanel.ttslua
  src/playercards/PlayerCardSpawner.ttslua
  src/playercards/SpawnBag.ttslua
  xml/playercards/PlayerCardPanel.xml
Labels: enhancement, optimization
