Repository argonui/SCED, pull requests merged in 2024-11, with the labels that each got.

#944 Updated Deck Importer's Attachment handling
  objects/ObjectSourceBag.830bd0/AttachmentHelper.7f4976.json
  src/accessories/AttachmentHelper.ttslua
  src/arkhamdb/ArkhamDb.ttslua
  src/arkhamdb/DeckImporter.ttslua
  src/arkhamdb/DeckInstructionGenerator.ttslua
  src/playermat/Zones.ttslua
Labels: enhancement

#949 Updated doom counter reset to remove ignored doom
  src/core/DoomInPlayCounter.ttslua
Labels: bugfix

#954 Removed orphan
  objects/Lovecrafter3077.b08d20.json
Labels: bugfix

#958 DES: Fixed XML creation
  src/playercards/cards/DreamEnhancingSerum.ttslua
Labels: bugfix

#961 Playermat: fixed investigator callback (used matColor instead of handColor)
  src/playermat/Playermat.ttslua
Labels: bugfix

#962 Kohaku: Fixed color for Bless Curse Manager messages
  src/chaosbag/BlessCurseManager.ttslua
  src/chaosbag/BlessCurseManagerApi.ttslua
  src/playercards/cards/KohakuNarukami.ttslua
Labels: bugfix

#960 Nil handling for Navigation Overlay
  src/core/NavigationOverlayHandler.ttslua
Labels: bugfix

#959 Deck Importer: updated taboo handling, Ancestral Knowledge randomization + zone
  src/arkhamdb/DeckImporter.ttslua
Labels: bugfix

#965 Fix player hand zone being upside down after using the rotate player mat function
  src/playermat/PlayermatApi.ttslua
Labels: bugfix

#964 Ability Tokens: Turned "randomize" into a context menu entry instead of using the TTS event
  src/core/UniversalActionAbilityToken.ttslua
Labels: optimization

#973 Hand Helper: Fixed formatting
  src/accessories/HandHelper.ttslua
Labels: maintenance

#974 Created XML for customizable' upgrade sheets
  TTSModManager.exe
  src/playercards/customizable/AlchemicalDistillationUpgradeSheet.ttslua
  src/playercards/customizable/UpgradeSheetLibrary.ttslua
Labels: optimization

#976 Upgradesheets: updated save function
  src/playercards/customizable/UpgradeSheetLibrary.ttslua
Labels: optimization

#978 Fixed `extraToken` for parallel Agnes
  objects/AllPlayerCards.15bb07/AgnesBakerParallelFront.02db0a.gmnotes
Labels: bugfix

#985 updated upkeep hotkey, removed upkeep (multihanded) hotkey
  src/core/GameKeyHandler.ttslua
  src/core/PlayArea.ttslua
Labels: optimization, maintenance

#992 Fixed tooltip position for XML windows
  xml/Global/DownloadWindow.xml
  xml/Global/PlayAreaGallery.xml
Labels: bugfix

#991 Fixed missing tag for dynamically added seal menu
  src/chaosbag/BlessCurseManager.ttslua
Labels: bugfix

#986 Upgradesheets: turned checkboxes into crosses
  src/playercards/customizable/UpgradeSheetLibrary.ttslua
  src/playermat/Playermat.ttslua
Labels: enhancement, maintenance

#981 Updated Campaign Importer/Exporter
  src/accessories/CampaignImporterExporter.ttslua
  src/accessories/CleanUpHelper.ttslua
Labels: enhancement, bugfix

#993 Bug Fixes to the Victory Display
  src/core/VictoryDisplay.ttslua
Labels: bugfix

#995 Updated damage/horror XML to detect if object spawns flipped
  src/core/DamageHorrorCounter.ttslua
Labels: bugfix

#998 Changed color to string
  src/playermat/Playermat.ttslua
Labels: maintenance

#999 Moving Token-Detaching to GlobalApi
  src/core/Global.ttslua
  src/core/GlobalApi.ttslua
  src/core/MythosArea.ttslua
  src/playermat/Playermat.ttslua
Labels: maintenance

#990 Updated notes and version number
  config.json
  objects/PatchNotes.f47225.luascriptstate
  src/core/Constants.ttslua
Labels: documentation

#1000 Bugfix for token detaching
  src/core/Global.ttslua
Labels: bugfix

#1001 Unified token discarding
  src/core/Global.ttslua
  src/core/GlobalApi.ttslua
  src/core/MythosArea.ttslua
  src/playercards/CardsThatSealTokens.ttslua
  src/playermat/Playermat.ttslua
  src/util/SearchLib.ttslua
Labels: bugfix, maintenance

#1009 Added token verification to cards that seal
  src/playercards/CardsThatSealTokens.ttslua
Labels: bugfix

#1005 Changed save functions
  objects/FlexTableControl.bd69bd.ttslua
  src/accessories/AdditionalVictoryPointsCard.ttslua
  src/accessories/TokenArranger.ttslua
  src/core/DataHelper.ttslua
  src/core/GUIDReferenceHandler.ttslua
  src/core/Global.ttslua
  src/core/MasterClueCounter.ttslua
  src/core/NavigationOverlayHandler.ttslua
  src/core/PlayArea.ttslua
  src/core/PlayAreaSelector.ttslua
  src/core/UniversalActionAbilityToken.ttslua
  src/core/token/TokenSpawnTracker.ttslua
  src/playercards/Search-A-Card.ttslua
  src/playermat/InvestigatorSkillTracker.ttslua
  src/util/ConnectionDrawingTool.ttslua
  src/util/TokenRemover.ttslua
Labels: optimization

#1006 Updated slot editing
  src/playermat/Playermat.ttslua
Labels: enhancement

#1008 Updated token stack size display and discard button search size
  src/playercards/CardsThatSealTokens.ttslua
  src/playermat/Playermat.ttslua
Labels: bugfix

#1007 Different attempt at token moving
  src/core/GameKeyHandler.ttslua
  src/core/Global.ttslua
  src/core/GlobalApi.ttslua
  src/core/MythosArea.ttslua
  src/playermat/Playermat.ttslua
Labels: optimization

#1010 Added "Token Draw Dummys" - typing numbers to draw x tokens
  config.json
  objects/PatchNotes.f47225.luascriptstate
  objects/TokenDrawDummy.dummy1.json
  objects/TokenDrawDummy.dummy2.json
  objects/TokenDrawDummy.dummy3.json
  objects/TokenDrawDummy.dummy4.json
  src/core/GUIDReferenceHandler.ttslua
  src/core/Global.ttslua
  src/core/tour/TourScript.ttslua
  src/playermat/TokenDrawDummy.ttslua
Labels: enhancement

#1016 Excluded cards that are held
  src/core/Global.ttslua
Labels: bugfix

#1013 Added git attributes for language detection on GitHub
  .gitattributes
Labels: documentation

#1020 Fixed picking up a card while it is falling
  src/core/Global.ttslua
  src/util/Trashcan.ttslua
Labels: bugfix

#1021 Removed token moving from TTS events
  config.json
  objects/PatchNotes.f47225.luascriptstate
  src/core/Constants.ttslua
  src/core/GameKeyHandler.ttslua
  src/core/Global.ttslua
  src/core/GlobalApi.ttslua
  src/playermat/Playermat.ttslua
  src/util/SearchLib.ttslua
  src/util/Trashcan.ttslua
Labels: bugfix

#1024 Fixed search lib
  config.json
  objects/PatchNotes.f47225.luascriptstate
  src/core/Constants.ttslua
  src/core/GameKeyHandler.ttslua
  src/core/Global.ttslua
  src/mythos/VictoryDisplay.ttslua
  src/playermat/Playermat.ttslua
  src/util/SearchLib.ttslua
Labels: bugfix

#1030 Investigator Callback: Fixed wrong color variable being used
  src/playermat/Playermat.ttslua
Labels: bugfix

#1026 Fixed scope for Generic Counter
  src/tokens/GenericCounter.ttslua
Labels: bugfix

#1028 Updated DeckImporter for tabooed UWM
  src/arkhamdb/DeckImporter.ttslua
Labels: bugfix

#1032 Added navigation overlay hotkeys
  src/core/GameKeyHandler.ttslua
Labels: enhancement
