Repository argonui/SCED, pull requests merged in 2024-09, with the labels that each got.

#852 Clean Up Helper: fixed mini card detection
  src/accessories/CleanUpHelper.ttslua
Labels: bugfix

#853 Attachment Helper: use metadata for matching and load rotation
  src/accessories/AttachmentHelper.ttslua
Labels: enhancement

#863 End the tour when deleted
  src/core/tour/TourManager.ttslua
  src/core/tour/TourStarter.ttslua
Labels: bugfix

#867 Attachment Helper: George skin
  src/accessories/AttachmentHelper.ttslua
Labels: official content

#865 Unbundled to fix scriptstates and add cycle to TMG
  objects/AllPlayerCards.15bb07/ArchibaldHudson.6cd7ec.gmnotes
  objects/AllPlayerCards.15bb07/ArsneRenard.2d493a.gmnotes
  objects/AllPlayerCards.15bb07/ClaireWilson.f96f2a.gmnotes
  objects/AllPlayerCards.15bb07/DeloresGadling.a6d899.gmnotes
  objects/AllPlayerCards.15bb07/DrMyaBadry.27e870.gmnotes
  objects/AllPlayerCards.15bb07/ElizabethConrad.3397ee.gmnotes
  objects/AllPlayerCards.15bb07/FalseAwakening.b43b00.json
  objects/AllPlayerCards.15bb07/HoracioMartinez.688f2d.gmnotes
  objects/AllPlayerCards.15bb07/JewelofSarnath.4258d6.gmnotes
  objects/AllPlayerCards.15bb07/LucasTetlow.041fd0.gmnotes
  objects/AllPlayerCards.15bb07/MirandaKeeper.9fdc8c.gmnotes
  objects/AllPlayerCards.15bb07/NovaMalone.e8f1e5.gmnotes
  objects/AllPlayerCards.15bb07/PrudenceDouglas.f32fa7.gmnotes
  objects/AllPlayerCards.15bb07/RaymondLoggins.1fca2a.gmnotes
  objects/AllPlayerCards.15bb07/SarahVanShaw.61df1c.gmnotes
  objects/AllPlayerCards.15bb07/SpecialAgentCallahan.d97c01.gmnotes
  objects/AllPlayerCards.15bb07/ThomasOlney.762460.gmnotes
  objects/Damagetokens.480bda/Damage.cd2a02.json
  objects/Damagetokens.93f4a0/Damage.cd2a02.json
  objects/Damagetokens.b0ef6c/Damage.cd2a02.json
  objects/LuaScriptState.luascriptstate
  objects/PatchNotes.f47225.luascriptstate
  objects/Playermat1White.8b081b.luascriptstate
  objects/Playermat2Orange.bd0ff4.luascriptstate
  objects/Playermat3Green.383d8b.luascriptstate
  objects/Playermat4Red.0840d5.luascriptstate
Labels: maintenance

#827 Moved side scenario spawn position one row higher
  modsettings/SnapPoints.json
  objects/ChallengeScenarios.9f6801.luascriptstate
  objects/StandaloneScenarios.77a5f9.luascriptstate
Labels: optimization

#873 Fixed DM play area image name
  src/core/PlayAreaImageData.ttslua
Labels: bugfix

#874 PlayerCard Panel: spawn investigators even if there are no other cards
  src/playercards/PlayerCardPanel.ttslua
Labels: bugfix

#875 Fixed playermat script states + Deck Importer Bug
  objects/Playermat1White.8b081b.luascriptstate
  objects/Playermat2Orange.bd0ff4.luascriptstate
  objects/Playermat3Green.383d8b.luascriptstate
  objects/Playermat4Red.0840d5.luascriptstate
  src/arkhamdb/DeckImporter.ttslua
Labels: bugfix

#880 Exclude custom sigs from weakness spread
  src/playercards/PlayerCardPanel.ttslua
Labels: bugfix

#876 Navigation Overlay: Handling for removed mats
  src/core/NavigationOverlayHandler.ttslua
Labels: bugfix

#878 Adapted tour and controls for unusual resolutions
  src/core/tour/TourCard.ttslua
  src/core/tour/TourManager.ttslua
  src/core/tour/TourScript.ttslua
  xml/Global/BottomBar.xml
Labels: bugfix

#877 Added a "shuffle discard into deck" button to playermats
  modsettings/CustomUIAssets.json
  objects/Playermat1White.8b081b.json
  objects/Playermat2Orange.bd0ff4.json
  objects/Playermat3Green.383d8b.json
  objects/Playermat4Red.0840d5.json
  src/playermat/Playermat.ttslua
  src/util/DeckLib.ttslua
Labels: enhancement

#882 Tour: updated script and added back button
  modsettings/CustomUIAssets.json
  src/core/tour/TourCard.ttslua
  src/core/tour/TourManager.ttslua
  src/core/tour/TourScript.ttslua
Labels: optimization

#883 Added a global XML UI for the Bless/Curse Manager
  modsettings/CustomUIAssets.json
  objects/LuaScriptState.luascriptstate
  src/chaosbag/BlessCurseManager.ttslua
  src/core/Global.ttslua
  xml/Global/BlessCurseManager.xml
  xml/Global/BottomBar.xml
  xml/Global/Global.xml
Labels: enhancement

#886 Bugfix: Upkeep button
  src/playermat/Playermat.ttslua
Labels: bugfix

#888 Added ability to specify a download repo version for a mod version
  src/core/Global.ttslua
Labels: enhancement
