Repository argonui/SCED, pull requests merged in 2024-10, with the labels that each got.

#887 Added an investigator placing callback
  objects/Fan-MadeAccessories.aa8b38.json
  objects/OptionPanelSource.830bd0.json
  objects/OptionPanelSource.830bd0/Subject5U-21Helper.1335e8.json
  src/core/Global.ttslua
  src/core/GlobalApi.ttslua
  src/core/token/TokenManagerApi.ttslua
  src/playermat/Playermat.ttslua
  src/playermat/Zones.ttslua
Labels: enhancement, bugfix, maintenance

#889 Search-A-Card: Added ability to spawn cards by ID (does not support Zoop IDs yet)
  src/playercards/CardSearch.ttslua
Labels: optimization

#892 Updated bottom bar
  xml/Global/BottomBar.xml
Labels: optimization, bugfix

#893 Removed obsolete campaign difficulty data
  src/core/DataHelper.ttslua
Labels: maintenance

#894 Updated custom card handling by player card panel / card index
  src/playercards/AllCardsBag.ttslua
Labels: bugfix

#891 Investigator Callback: Added 2nd zone for token bags
  src/playermat/Playermat.ttslua
  src/playermat/Zones.ttslua
Labels: optimization

#895 Updated doom counting
  src/accessories/CleanUpHelper.ttslua
  src/core/DoomCounter.ttslua
  src/core/DoomInPlayCounter.ttslua
  src/playermat/ClueCounter.ttslua
  src/util/SearchLib.ttslua
Labels: enhancement

#896 Added helper for The Red Clock
  objects/AllPlayerCards.15bb07/TheRedClock2.814c79.json
  objects/AllPlayerCards.15bb07/TheRedClock5.696894.json
  src/core/Global.ttslua
  src/core/token/TokenManagerApi.ttslua
  src/playercards/cards/TheRedClock.ttslua
  src/util/TokenSpawnTool.ttslua
  xml/playercards/TheRedClock.xml
Labels: enhancement

#898 Fixed tooltip offset for Option Panel
  xml/Global/OptionPanel.xml
Labels: bugfix

#903 Additional way of stopping objects from falling through the playermat
  src/playermat/Playermat.ttslua
Labels: optimization

#900 Added additional instruction to doom counter
  src/core/DoomCounter.ttslua
Labels: optimization

#904 Search-A-Card: Added support for ID searching
  objects/Search-A-Card.24051a.json
  src/playercards/Search-A-Card.ttslua
Labels: optimization

#902 Victory Display: Added button to spawn additional VP card
  config.json
  objects/Fan-MadeAccessories.aa8b38.json
  objects/ObjectSourceBag.830bd0.json
  objects/ObjectSourceBag.830bd0/AdditionalVictoryPoints.958bc0.json
  objects/ObjectSourceBag.830bd0/AttachmentHelper.7f4976.json
  objects/ObjectSourceBag.830bd0/AttachmentHelper.7f4976/AttachmentHelper.d45664.json
  objects/ObjectSourceBag.830bd0/CYOACampaignGuides.e87ea2.json
  objects/ObjectSourceBag.830bd0/CleanUpHelper.26cf4b.json
  objects/ObjectSourceBag.830bd0/DisplacementTool.0f1374.json
  objects/ObjectSourceBag.830bd0/HandHelper.450688.json
  objects/ObjectSourceBag.830bd0/SearchAssistant.17aed0.json
  objects/ObjectSourceBag.830bd0/Subject5U-21Helper.1335e8.json
  src/accessories/AdditionalVictoryPointsCard.ttslua
  src/core/GUIDReferenceHandler.ttslua
  src/core/Global.ttslua
  src/core/VictoryDisplay.ttslua
  src/playermat/Playermat.ttslua
  xml/Global/OptionPanel.xml
Labels: enhancement

#907 Added search and filter to download menu
  src/core/Global.ttslua
  xml/Global/DownloadWindow.xml
Labels: enhancement

#908 Fixed navigation overlay non-playermat cameras
  src/core/GameKeyHandler.ttslua
  src/core/NavigationOverlayApi.ttslua
  src/core/NavigationOverlayHandler.ttslua
Labels: bugfix

#909 Removal of unneeded data from Data Helper
  src/core/DataHelper.ttslua
Labels: maintenance

#912 Updated "Take into Threat Area" Game Key
  src/core/GameKeyHandler.ttslua
Labels: optimization

#910 Added function for playermat moving / rotating
  src/core/Global.ttslua
  src/playermat/PlayermatApi.ttslua
Labels: enhancement

#916 Added additional check for objects leaving a zone
  src/core/Global.ttslua
Labels: bugfix

#917 Updated drawing tool to keep existing lines
  src/util/ConnectionDrawingTool.ttslua
Labels: bugfix

#915 Clean Up Helper: updated prelude list and some small code changes
  src/accessories/CleanUpHelper.ttslua
Labels: optimization

#911 Updated deck instructions and added file for constants
  modsettings/TabStates.json
  src/accessories/CardBackEnhancer.ttslua
  src/arkhamdb/DeckInstructionGenerator.ttslua
  src/core/Constants.ttslua
  src/core/Global.ttslua
  src/core/MythosArea.ttslua
  src/playermat/Playermat.ttslua
Labels: optimization

#921 4.0 patch notes
  objects/PatchNotes.f47225.luascriptstate
  objects/PatchNotes.f47225.ttslua
Labels: documentation, optimization

#922 Updated Chaos Token stat tracker and added VS Code build task
  .vscode/tasks.json
  objects/ChaosBagStatTracker.766620.json
  src/chaosbag/ChaosBagStatTracker.ttslua
  src/core/GUIDReferenceHandler.ttslua
  src/core/Global.ttslua
Labels: enhancement

#901 Updated Campaign Exporter / Importer
  objects/CampaignImporterExporter.334ee3.json
  src/accessories/CampaignImporterExporter.ttslua
  src/accessories/TokenArranger.ttslua
  src/accessories/TokenArrangerApi.ttslua
  src/core/GUIDReferenceHandler.ttslua
  src/core/NavigationOverlayApi.ttslua
  src/core/NavigationOverlayHandler.ttslua
  src/playermat/Playermat.ttslua
  src/playermat/PlayermatApi.ttslua
  src/util/TokenRemover.ttslua
Labels: enhancement, optimization, maintenance

#925 Fixed cards modifying default value for tokens
  src/core/Global.ttslua
  src/core/token/TokenManagerApi.ttslua
  src/util/TokenSpawnTool.ttslua
Labels: bugfix

#924 Playermat: Updated onCollisionEnter() and followup functions
  src/playermat/Playermat.ttslua
Labels: maintenance

#926 Updated action token handling for Clean Up Helper
  src/accessories/CleanUpHelper.ttslua
  src/playermat/Playermat.ttslua
  src/playermat/PlayermatApi.ttslua
Labels: bugfix

#930 Fixed position for encounter discard
  src/core/Constants.ttslua
Labels: bugfix

#934 Disabled mini card snapping
  objects/AllPlayerCards.15bb07/AlessandraZorzi.cea425.json
  objects/AllPlayerCards.15bb07/AminaZidane.458edc.json
  objects/AllPlayerCards.15bb07/CarsonSinclair.c0f76c.json
  objects/AllPlayerCards.15bb07/CharlieKane.4deeff.json
  objects/AllPlayerCards.15bb07/DarrellSimmons.3b3b7a.json
  objects/AllPlayerCards.15bb07/HankSamson.3764cc.json
  objects/AllPlayerCards.15bb07/KateWinthrop.ce2323.json
  objects/AllPlayerCards.15bb07/KhakuNarukami.cea427.json
  objects/AllPlayerCards.15bb07/KymaniJones.d3d7fb.json
  objects/AllPlayerCards.15bb07/SummonedServitor.d187dd.json
  objects/AllPlayerCards.15bb07/VincentLee.43ad8a.json
  objects/AllPlayerCards.15bb07/WilsonRichards.ceb426.json
Labels: bugfix

#932 Added library file for memory bags
  objects/ChallengeScenarios.9f6801.json
  objects/ChallengeScenarios.9f6801.ttslua
  objects/StandaloneScenarios.77a5f9.json
  objects/StandaloneScenarios.77a5f9.ttslua
  src/MemoryBag.ttslua
Labels: enhancement

#940 Updates to "Remove a use" hotkey
  src/core/GameKeyHandler.ttslua
Labels: optimization

#942 Added XML UI assets to objects that use them
  objects/AllPlayerCards.15bb07/Analysis.80285f.json
  objects/AllPlayerCards.15bb07/ClaypoolsFurs.c1f999.json
  objects/AllPlayerCards.15bb07/CustomModifications.d2252d.json
  objects/AllPlayerCards.15bb07/Dream-EnhancingSerum.98c5af.json
  objects/AllPlayerCards.15bb07/FalseCovenant2.3442f5.json
  objects/AllPlayerCards.15bb07/FamilyInheritance.394603.json
  objects/AllPlayerCards.15bb07/HeavyFurs.275450.json
  objects/AllPlayerCards.15bb07/KhakuNarukami.54eaa7.json
  objects/AllPlayerCards.15bb07/NkosiMabati3.6c5628.json
  objects/AllPlayerCards.15bb07/StellaClark.00e18e.json
  objects/AllPlayerCards.15bb07/Strong-Armed1.294d6.json
  objects/AllPlayerCards.15bb07/TheRedClock2.814c79.json
  objects/AllPlayerCards.15bb07/TheRedClock5.696894.json
  objects/AllPlayerCards.15bb07/ThirdTimesaCharm2.45956a.json
  objects/AllPlayerCards.15bb07/WellConnected.66b7d5.json
  objects/AllPlayerCards.15bb07/WellConnected3.170127.json
  objects/AllPlayerCards.15bb07/WendyAdams.fc1d17.json
  objects/AllPlayerCards.15bb07/WendyAdamsParallelBack.4232d9.json
  objects/Playermat1White.8b081b.json
  objects/Playermat2Orange.bd0ff4.json
  objects/Playermat3Green.383d8b.json
  objects/Playermat4Red.0840d5.json
Labels: bugfix

#945 Updated FAQ to v2.3
  objects/LatestFAQ.faqfaq.json
Labels: official content

#939 Fixed card drawing with reshuffle
  src/playermat/Playermat.ttslua
Labels: bugfix
