Repository argonui/SCED, pull requests merged in 2024-07, with the labels that each got.

#732 [Clean Up Helper] Bugfix for skipping playermats
  src/accessories/CleanUpHelper.ttslua
Labels: bugfix

#730 Context Menus and Token Spawning
  src/accessories/PhaseTracker.ttslua
  src/accessories/UnderworldMarketHelper.ttslua
  src/core/MythosArea.ttslua
  src/core/UniversalActionAbilityToken.ttslua
  src/core/token/TokenManager.ttslua
  src/core/token/TokenSpawnTracker.ttslua
  src/core/token/TokenSpawnTrackerApi.ttslua
  src/playercards/CardsThatRedrawTokens.ttslua
  src/playercards/CardsWithHelper.ttslua
  src/playercards/Tarotcard.ttslua
  src/playercards/cards/BookofLivingMyths.ttslua
  src/playercards/cards/EmpiricalHypothesis.ttslua
  src/playercards/cards/FamilyInheritance.ttslua
  src/playercards/cards/NkosiMabati3.ttslua
  src/playercards/cards/ScrollofSecrets.ttslua
  src/playercards/cards/ShortSupply.ttslua
  src/playercards/cards/Tekeli-li.ttslua
  src/playermat/Playermat.ttslua
Labels: optimization

#733 Added coloring to player names in broadcasts
  src/core/GameKeyHandler.ttslua
  src/playermat/Playermat.ttslua
Labels: optimization

#740 Code maintenance
  src/accessories/SearchAssistant.ttslua
  src/core/VictoryDisplay.ttslua
  src/playercards/cards/KohakuNarukami.ttslua
  src/playermat/Playermat.ttslua
  src/util/DeckLib.ttslua
  xml/playercards/KohakuNarukami.xml
Labels: optimization

#741 Added 1 frame delay to avoid error when exiting
  src/core/Global.ttslua
Labels: bugfix

#744 Updated Clean Up Helper
  src/accessories/CleanUpHelper.ttslua
Labels: optimization, bugfix

#746 Threat Area Gamekey: Added rounding and hand zone support
  src/core/GUIDReferenceHandler.ttslua
  src/core/GameKeyHandler.ttslua
Labels: enhancement

#747 SearchLib: added missing local declaration
  src/util/SearchLib.ttslua
Labels: documentation, optimization

#745 Updated Playermat
  src/core/Global.ttslua
  src/playermat/Playermat.ttslua
Labels: bugfix

#753 Updates for Search Assistant
  src/accessories/SearchAssistant.ttslua
Labels: enhancement

#754 Update for cards with helper
  src/playercards/CardsThatRedrawTokens.ttslua
  src/playercards/CardsWithHelper.ttslua
  src/playercards/cards/BookofLivingMyths.ttslua
  src/playercards/cards/EmpiricalHypothesis.ttslua
  src/playercards/cards/FamilyInheritance.ttslua
  src/playercards/cards/KohakuNarukami.ttslua
  src/playercards/cards/WellConnected.ttslua
Labels: optimization, bugfix

#759 Fixed hand helper being loaded first
  src/accessories/HandHelper.ttslua
  src/playermat/Playermat.ttslua
Labels: bugfix

#763 Updated hand zone handling for helpers
  src/core/Global.ttslua
Labels: bugfix

#770 Reset clue spawning for locations when new scenario starts
  src/core/MythosArea.ttslua
  src/core/token/TokenSpawnTrackerApi.ttslua
Labels: enhancement

#772 Bugfix for single cards in deck area
  src/arkhamdb/DeckImporter.ttslua
Labels: bugfix

#771 Added clue replenishing to hotkey
  src/core/GameKeyHandler.ttslua
  src/core/PlayArea.ttslua
  src/core/token/TokenManager.ttslua
  src/util/SearchLib.ttslua
  src/util/TokenSpawnTool.ttslua
Labels: enhancement

#778 Update playarea when removing locations with hotkeys
  src/core/GameKeyHandler.ttslua
  src/core/PlayAreaApi.ttslua
Labels: bugfix

#780 Fixed token rotation from last action token persisting
  src/util/TokenSpawnTool.ttslua
Labels: bugfix

#779 DeckLib: Flip cards instantly
  src/util/DeckLib.ttslua
Labels: bugfix

#783 Removal of rules index
  objects/RulesIndex.91c83e.json
Labels: bugfix

#781 Bugfixes for "Remove One Use" hotkey
  src/core/GameKeyHandler.ttslua
  src/core/GenericCounter.ttslua
  src/util/TokenSpawnTool.ttslua
Labels: bugfix

#774 Added arkham.build support
  src/arkhamdb/ArkhamDb.ttslua
  src/arkhamdb/Configuration.ttslua
  src/arkhamdb/DeckImporter.ttslua
Labels: enhancement

#787 Added helper to Nkosi
  src/playercards/cards/NkosiMabati3.ttslua
Labels: optimization
