Repository argonui/SCED, pull requests merged in 2025-06, with the labels that each got.

#1277 Updated Clean Up Helper
  src/accessories/CleanUpHelper.ttslua
Labels: enhancement, optimization

#1280 Updated playermat option panel
  modsettings/CustomUIAssets.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Playermat.111111.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Playermat.111111.luascriptstate
  objects/Playermat1White.8b081b.json
  objects/Playermat1White.8b081b.luascriptstate
  objects/Playermat2Orange.bd0ff4.json
  objects/Playermat2Orange.bd0ff4.luascriptstate
  objects/Playermat3Green.383d8b.json
  objects/Playermat3Green.383d8b.luascriptstate
  objects/Playermat4Red.0840d5.json
  objects/Playermat4Red.0840d5.luascriptstate
  src/playermat/Playermat.ttslua
  src/playermat/PlayermatApi.ttslua
Labels: optimization

#1284 Updated DeckLib
  src/util/DeckLib.ttslua
Labels: bugfix

#1281 Gabriel Carillo Helper
  objects/AllPlayerCards.15bb07/GabrielCarillo1.7e1088.json
  src/playercards/cards/GabrielCarillo1.ttslua
  xml/playercards/GabrielCarillo1.xml
Labels: enhancement

#1286 Additional secret for Elsie Malone (Night of Vespers)
  src/playermat/Playermat.ttslua
Labels: enhancement

#1283 Deck Importer updates for custom content
  src/Global/Global.ttslua
  src/Global/GlobalApi.ttslua
  src/arkhamdb/ArkhamDb.ttslua
  src/arkhamdb/DeckImporter.ttslua
  src/arkhamdb/DeckImporterApi.ttslua
  src/playercards/AllCardsBag.ttslua
  src/playercards/AllCardsBagApi.ttslua
  src/util/CoroutineLib.ttslua
Labels: enhancement

#1292 Fixed token image selection for Nkosi
  src/playercards/cards/NkosiMabati3.ttslua
Labels: bugfix

#1296 Improved error handling for AllCardsBag
  src/playercards/AllCardsBag.ttslua
Labels: bugfix

#1295 Allow buyers guide to be rotated
  src/util/BuyersGuide.ttslua
Labels: bugfix

#1302 Updated patch notes
  objects/AllPlayerCards.15bb07/BookofLivingMyths.c5fb1f.json
  objects/AllPlayerCards.15bb07/ClaypoolsFurs.c1f999.json
  objects/AllPlayerCards.15bb07/FalseCovenant2.3442f5.json
  objects/AllPlayerCards.15bb07/KhakuNarukami.54eaa7.json
  objects/AllPlayerCards.15bb07/NkosiMabati3.6c5628.json
  objects/PatchNotes.f47225.luascriptstate
Labels: documentation

#1311 Continue deck import if content can't be found
  src/Global/Global.ttslua
  src/Global/GlobalApi.ttslua
  src/arkhamdb/ArkhamDb.ttslua
Labels: enhancement

#1313 Slightly adjust helper spawn data
  src/playermat/PlayermatApi.ttslua
Labels: bugfix

#1321 Update Search-A-Card to support cyrillic characters
  src/playercards/Search-A-Card.ttslua
  src/util/utf8.ttslua
Labels: optimization

#1320 Add scenario count to Download Window
  src/Global/Global.ttslua
  xml/Global/DownloadWindow.xml
Labels: enhancement

#1322 Internationalization (i18n) of Global UI
  .gitignore
  locales/_po_to_lua_converter.py
  locales/_sync_po_files.py
  locales/de.po
  locales/en.po
  locales/es.po
  locales/fr.po
  locales/it.po
  locales/ru.po
  locales/zh_CN.po
  locales/zh_TW.po
  modsettings/CustomUIAssets.json
  objects/AllPlayerCards.15bb07/ElleRubash2.43c3e0.json
  objects/AllPlayerCards.15bb07/FamilyInheritance.394603.json
  objects/AllPlayerCards.15bb07/LugerP08.tdc050.json
  objects/AllPlayerCards.15bb07/TheRedClock2.814c79.json
  objects/AllPlayerCards.15bb07/TheRedClock5.696894.json
  objects/CleanUpHelper.26cf4b.json
  objects/LuaScriptState.luascriptstate
  src/Global/Global.ttslua
  src/Global/i18n.ttslua
  src/Global/i18nApi.ttslua
  src/Global/i18nData.ttslua
  src/core/NavigationOverlayHandler.ttslua
  xml/Global/BottomBar.xml
  xml/Global/DownloadWindow.xml
  xml/Global/NavigationOverlay.xml
  xml/Global/OptionPanel.xml
  xml/Global/PlayAreaGallery.xml
  xml/accessories/CleanUpHelper.xml
  xml/playercards/ElleRubash2.xml
  xml/playercards/FamilyInheritance.xml
  xml/playercards/Luger.xml
  xml/playercards/TheRedClock.xml
Labels: enhancement
