Repository argonui/SCED, pull requests merged in 2025-02, with the labels that each got.

#1105 Added message variation to token drawing stats
  src/core/Global.ttslua
Labels: enhancement

#1106 Minor code improvements for Search Assistant
  src/accessories/SearchAssistant.ttslua
Labels: maintenance

#1112 Well Connected delay
  src/playercards/cards/WellConnected.ttslua
Labels: bugfix

#1110 Fixed option not applying onLoad() to damage/horror counters
  src/tokens/DamageHorrorCounter.ttslua
Labels: bugfix

#1115 Added a general function for card readying
  objects/AllPlayerCards.15bb07/LugerP08.tdc050.json
  src/core/Global.ttslua
  src/core/GlobalApi.ttslua
  src/playarea/PlayArea.ttslua
  src/playarea/PlayAreaApi.ttslua
  src/playercards/cards/Luger.ttslua
  src/playercards/cards/LugerP08.ttslua
  src/playermat/Playermat.ttslua
Labels: enhancement

#1116 Added debug spawn function
  src/playercards/AllCardsBag.ttslua
Labels: enhancement

#1117 Added debug function to force specific option panel state
  src/core/CampaignImporterExporter.ttslua
  src/core/Constants.ttslua
  src/core/Global.ttslua
  src/core/GlobalApi.ttslua
  xml/Global/BottomBar.xml
Labels: enhancement

#1109 updated patch notes
  config.json
  objects/AllPlayerCards.15bb07/AmpleSupplies2.tdc089.gmnotes
  objects/AllPlayerCards.15bb07/AmpleSupplies2.tdc089.json
  objects/AllPlayerCards.15bb07/BloodofThoth.tdc065.json
  objects/AllPlayerCards.15bb07/BumsRush.tdc055.json
  objects/AllPlayerCards.15bb07/CosmicRevelation1.tdc041.json
  objects/AllPlayerCards.15bb07/DoubleDown2.tdc107.json
  objects/AllPlayerCards.15bb07/GiftofNodens5.tdc094.json
  objects/AllPlayerCards.15bb07/GloriaGoldberg.abc014.json
  objects/AllPlayerCards.15bb07/HandHook.tdc082.json
  objects/AllPlayerCards.15bb07/LostArcana3.tdc078.json
  objects/AllPlayerCards.15bb07/Obscure2.tdc060.json
  objects/AllPlayerCards.15bb07/QuickWitted1.tdc042.gmnotes
  objects/AllPlayerCards.15bb07/QuickWitted1.tdc042.json
  objects/AllPlayerCards.15bb07/SacredOath5.tdc121.json
  objects/AllPlayerCards.15bb07/SacredOath5.tdc122.json
  objects/AllPlayerCards.15bb07/SacredOath5.tdc123.json
  objects/AllPlayerCards.15bb07/ScientificStudiesGrant2.tdc044.json
  objects/AllPlayerCards.15bb07/WorkingaHunch2.tdc045.json
  objects/Fan-MadeAccessories.aa8b38/DoomCounterBag.a82b88/DoomCounter.a7cc48.json
  objects/ObjectSourceBag.830bd0/AttachmentHelper.7f4976.json
  objects/PatchNotes.f47225.luascriptstate
  src/core/Constants.ttslua
Labels: documentation

#1123 Update to dynamic tokens
  objects/Dynamictokens.a3efc9/DynamicToken.910e09.json
  src/core/Global.ttslua
  src/tokens/DynamicToken.ttslua
Labels: optimization

#1125 Fixed disabling draw button
  src/playermat/Playermat.ttslua
Labels: bugfix

#1124 Search Assistant: Fixed dummy hand position for rotated playermats
  src/accessories/SearchAssistant.ttslua
Labels: bugfix

#1130 Ensure "reshuffling" always places the deck at the correct position
  src/mythos/MythosArea.ttslua
Labels: bugfix

#1133 Unified highlighting
  src/core/Global.ttslua
  src/mythos/DoomInPlayCounter.ttslua
  src/playercards/cards/ElleRubash2.ttslua
  src/playercards/cards/KohakuNarukami.ttslua
  src/playercards/cards/StellaClark.ttslua
  src/playercards/cards/TheRedClock.ttslua
  src/tokens/GenericCounter.ttslua
  src/tokens/TokenManagerApi.ttslua
  src/tokens/TokenSpawnTool.ttslua
  src/tokens/UniversalActionAbilityToken.ttslua
Labels: optimization

#1138 Removed released beta cards
  objects/AdditionalPlayerCards.2cba6b.json
  objects/AdditionalPlayerCards.2cba6b/AliceLuxley2.94f23b.gmnotes
  objects/AdditionalPlayerCards.2cba6b/AliceLuxley2.94f23b.json
  objects/AdditionalPlayerCards.2cba6b/SwordCane2.9c32e2.gmnotes
  objects/AdditionalPlayerCards.2cba6b/SwordCane2.9c32e2.json
Labels: maintenance

#1145 Added support for Eldritch Brand attachments (arkham.build feature)
  src/arkhamdb/DeckImporter.ttslua
Labels: optimization

#1141 Updates to some cards
  src/playercards/cards/ElleRubash2.ttslua
  src/playercards/cards/GiftofNodens.ttslua
  src/playercards/cards/KohakuNarukami.ttslua
  src/playercards/cards/LuckyPenny.ttslua
  src/playercards/cards/LugerP08.ttslua
  src/playercards/cards/ShortSupply.ttslua
Labels: bugfix, maintenance

#1144 Fixed token remover state saving for exporter
  src/core/CampaignImporterExporter.ttslua
Labels: bugfix

#1150 Fixed Inspiring Presence (2)'s level
  objects/AllPlayerCards.15bb07/InspiringPresence2.tdc029.gmnotes
Labels: bugfix

#1151 Fixed Robert Castaigne (4)'s level
  objects/AllPlayerCards.15bb07.json
  objects/AllPlayerCards.15bb07/RobertCastaigne4.tdc062.gmnotes
  objects/AllPlayerCards.15bb07/RobertCastaigne4.tdc062.json
Labels: bugfix

#1148 Added ability to respawn playermats
  objects/ObjectSourceBag.830bd0.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/ClueCounter.111120.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Clues.111119.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Cluetokens.111118.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Cluetokens.111118/Custom_Tile.a3fb6c.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Damage.111117.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Damagetokens.111116.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Damagetokens.111116/Damage.cd2a02.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Doomtokens.111121.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Doomtokens.111121/Custom_Tile.a3fb6c.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Dynamictokens.111123.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Dynamictokens.111123/DynamicToken.910e09.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/HandTrigger.111122.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Horror.111115.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Horrortokens.111114.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Horrortokens.111114/Horror.36be72.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/InvestigatorSkillTracker.111124.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Playermat.111111.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Playermat.111111.luascriptstate
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Resources.111113.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Resourcetokens.11112.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Resourcetokens.11112/Resource.910e09.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Resourcetokens.11112/Resource.910e09/Ammo.00d19a.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Resourcetokens.11112/Resource.910e09/Bounty.a5ce94.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Resourcetokens.11112/Resource.910e09/Charge.a5ce94.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Resourcetokens.11112/Resource.910e09/Evidence.a5ce94.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Resourcetokens.11112/Resource.910e09/Offering.2b4348.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Resourcetokens.11112/Resource.910e09/Secret.7a4a9a.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Resourcetokens.11112/Resource.910e09/Supply.2b4628.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/TokenDiscardZone.111128.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/TokenDrawDummy.111127.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/TokenRemover.111126.json
  objects/ObjectSourceBag.830bd0/PlayermatObjects.daniel/Trash.111125.json
  objects/PatchNotes.f47225.luascriptstate
  src/core/Global.ttslua
  src/playermat/Playermat.ttslua
  src/playermat/Zones.ttslua
  xml/Global/OptionPanel.xml
Labels: enhancement

#1142 Set default values for deck importer variables
  src/arkhamdb/DeckImporter.ttslua
  src/arkhamdb/DeckImporterApi.ttslua
Labels: bugfix

#1146 Added context menu item to downloaded objects for reloading
  src/core/Global.ttslua
Labels: enhancement

#1159 Added victory display check for "Remove One Use" gamekey
  src/core/GameKeyHandler.ttslua
Labels: bugfix

#1149 Updated mythos area with local coordinates for encounter deck
  objects/MythosArea.9f334f.json
  src/core/Constants.ttslua
  src/mythos/DoomCounter.ttslua
  src/mythos/MythosArea.ttslua
  src/mythos/MythosAreaApi.ttslua
  src/playermat/Playermat.ttslua
Labels: optimization

#1153 Improved tag handling for Encounter Card Bag
  src/mythos/AllEncounterCardsBag.ttslua
Labels: optimization
