Repository argonui/SCED, pull requests merged in 2025-09, with the labels that each got.

#1454 Allow data combining for replacement cards
  objects/AllPlayerCards.15bb07/AlchemicalDistillationUpgradeSheet.156166.json
  objects/AllPlayerCards.15bb07/CustomModificationsUpgradeSheet.4104bf.json
  objects/AllPlayerCards.15bb07/DamningTestimonyUpgradeSheet.dc4a62.json
  objects/AllPlayerCards.15bb07/EmpiricalHypothesisUpgradeSheet.0c46a7.json
  objects/AllPlayerCards.15bb07/FriendsinLowPlacesUpgradeSheet.9fb3b9.json
  objects/AllPlayerCards.15bb07/GrizzledUpgradeSheet.ef8f08.json
  objects/AllPlayerCards.15bb07/HonedInstinctUpgradeSheet.ba0e34.json
  objects/AllPlayerCards.15bb07/HuntersArmorUpgradeSheet.d2d01b.json
  objects/AllPlayerCards.15bb07/HyperphysicalShotcasterUpgradeSheet.a4eec2.json
  objects/AllPlayerCards.15bb07/LivingInkUpgradeSheet.19a05b.json
  objects/AllPlayerCards.15bb07/MakeshiftTrapUpgradeSheet.64dfce.json
  objects/AllPlayerCards.15bb07/PocketMultiToolUpgradeSheet.d706e7.json
  objects/AllPlayerCards.15bb07/PowerWordUpgradeSheet.0d9481.json
  objects/AllPlayerCards.15bb07/PowerWordUpgradeSheetTaboo.ebce85.json
  objects/AllPlayerCards.15bb07/RunicAxeUpgradeSheetTaboo.4d729b.json
  objects/AllPlayerCards.15bb07/SummonedServitorUpgradeSheet.5397a6.json
  objects/AllPlayerCards.15bb07/TheRavenQuillUpgradeSheet.23b96a.json
  src/deckbuilder/DeckImporter.ttslua
  src/mythos/AllEncounterCardsBag.ttslua
  src/playercards/AllCardsBag.ttslua
  src/playercards/CardSpawner.ttslua
  src/playercards/PlayerCardSpawner.ttslua
  src/playercards/Search-A-Card.ttslua
  src/playercards/SpawnBag.ttslua
  src/playercards/customizable/UpgradeSheetLibrary.ttslua
Labels: enhancement, optimization

#1453 Add support for Navigation Overlay presets
  src/Global/Global.ttslua
  src/core/Constants.ttslua
  src/core/NavigationOverlayApi.ttslua
  src/core/NavigationOverlayHandler.ttslua
Labels: optimization

#1463 Taboo handling for bonded cards
  src/playercards/AllCardsBag.ttslua
Labels: bugfix

#1461 Portuguese Translation
  locales/pt.po
  src/Global/i18n.ttslua
  src/Global/i18nData.ttslua
  xml/Global/OptionPanel.xml
Labels: i18n

#1469 Bug fix for resource counter spawn
  src/Global/Global.ttslua
Labels: bugfix

#1473 feat: update ko translations (tour..)
  locales/ko.po
Labels: i18n

#1479 Fixed german subtitle in Film Fatale image
  objects/FilmFatale.45e513.json
Labels: bugfix

#1481 Allow Charlie helper to ready Jacob Morrison
  src/Global/Global.ttslua
  src/Global/GlobalApi.ttslua
  src/playercards/cards/CharlieKane.ttslua
Labels: bugfix

#1482 Fixed wrong comment in playermatapi
  src/playermat/PlayermatApi.ttslua
Labels: documentation, bugfix
